export const categories = [
    {
        icon: '🌟',
        link: '/routes/popular',
        en: 'Popular',
        zh: '热门',
    },
    {
        icon: '💬',
        link: '/routes/social-media',
        en: 'Social Media',
        zh: '社交媒体',
    },
    {
        icon: '📱',
        link: '/routes/new-media',
        en: 'New media',
        zh: '新媒体',
    },
    {
        icon: '📰',
        link: '/routes/traditional-media',
        en: 'Traditional media',
        zh: '传统媒体',
    },
    {
        icon: '💬️',
        link: '/routes/bbs',
        en: 'BBS',
        zh: '论坛',
    },
    {
        icon: '🖊️️',
        link: '/routes/blog',
        en: 'Blog',
        zh: '博客',
    },
    {
        icon: '💻',
        link: '/routes/programming',
        en: 'Programming',
        zh: '编程',
    },
    {
        icon: '🎨️',
        link: '/routes/design',
        en: 'Design',
        zh: '设计',
    },
    {
        icon: '🎥',
        link: '/routes/live',
        en: 'Live',
        zh: '直播',
    },
    {
        icon: '🔊',
        link: '/routes/multimedia',
        en: 'Multimedia',
        zh: '音视频',
    },
    {
        icon: '🖼️',
        link: '/routes/picture',
        en: 'Picture',
        zh: '图片',
    },
    {
        icon: '🎨️',
        link: '/routes/anime',
        en: 'ACG',
        zh: '二次元',
    },
    {
        icon: '🔄',
        link: '/routes/program-update',
        en: 'Application Updates',
        zh: '程序更新',
    },
    {
        icon: '🎓',
        link: '/routes/university',
        en: 'University',
        zh: '大学通知',
    },
    {
        icon: '❗️',
        link: '/routes/forecast',
        en: 'Forecast and Alerts',
        zh: '预报预警',
    },
    {
        icon: '🛫',
        link: '/routes/travel',
        en: 'Travel',
        zh: '出行旅游',
    },
    {
        icon: '🛍️',
        link: '/routes/shopping',
        en: 'Shopping',
        zh: '购物',
    },
    {
        icon: '🎮',
        link: '/routes/game',
        en: 'Gaming',
        zh: '游戏',
    },
    {
        icon: '📚',
        link: '/routes/reading',
        en: 'Reading',
        zh: '阅读',
    },
    {
        icon: '📢',
        link: '/routes/government',
        en: 'Government',
        zh: '政务消息',
    },
    {
        icon: '📖',
        link: '/routes/study',
        en: 'Study',
        zh: '学习',
    },
    {
        icon: '🔬',
        link: '/routes/journal',
        en: 'Scientific Journal',
        zh: '科学期刊',
    },
    {
        icon: '💰',
        link: '/routes/finance',
        en: 'Finance',
        zh: '金融',
    },
    {
        icon: '🔍',
        link: '/routes/other',
        en: 'Uncategorized',
        zh: '其他',
    },
];
