export default {
    'jiemian.com': {
        _name: '界面新闻',
        '.': [
            {
                title: '首页 - 科技',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/65.html'],
                target: '/jiemian/lists/65',
            },
            {
                title: '首页 - 金融',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/9.html'],
                target: '/jiemian/lists/9',
            },
            {
                title: '首页 - 证券',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/112.html'],
                target: '/jiemian/lists/112',
            },
            {
                title: '首页 - 地产',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/62.html'],
                target: '/jiemian/lists/62',
            },
            {
                title: '首页 - 汽车',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/51.html'],
                target: '/jiemian/lists/51',
            },
            {
                title: '首页 - 健康',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/472.html'],
                target: '/jiemian/lists/472',
            },
            {
                title: '首页 - 地方',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/city/main/277.html'],
                target: '/jiemian/city/main/277',
            },
            {
                title: '首页 - 大湾区',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/680.html'],
                target: '/jiemian/lists/680',
            },
            {
                title: '首页 - 元宇宙',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/704.html'],
                target: '/jiemian/lists/704',
            },
            {
                title: '首页 - 文旅',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/105.html'],
                target: '/jiemian/lists/105',
            },
            {
                title: '首页 - 数据',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/154.html'],
                target: '/jiemian/lists/154',
            },
            {
                title: '首页 - ESG',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/712.html'],
                target: '/jiemian/lists/712',
            },
            {
                title: '首页 - 双碳',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/877.html'],
                target: '/jiemian/lists/877',
            },
            {
                title: '首页 - 电厂',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shou-ye',
                source: ['/lists/872.html'],
                target: '/jiemian/lists/872',
            },
            {
                title: '商业 - 科技',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/65.html'],
                target: '/jiemian/lists/65',
            },
            {
                title: '商业 - 地产',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/62.html'],
                target: '/jiemian/lists/62',
            },
            {
                title: '商业 - 汽车',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/51.html'],
                target: '/jiemian/lists/51',
            },
            {
                title: '商业 - 消费',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/31.html'],
                target: '/jiemian/lists/31',
            },
            {
                title: '商业 - 工业',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/28.html'],
                target: '/jiemian/lists/28',
            },
            {
                title: '商业 - 时尚',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/68.html'],
                target: '/jiemian/lists/68',
            },
            {
                title: '商业 - 交通',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/30.html'],
                target: '/jiemian/lists/30',
            },
            {
                title: '商业 - 医药',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/472.html'],
                target: '/jiemian/lists/472',
            },
            {
                title: '商业 - 互联网',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/851.html'],
                target: '/jiemian/lists/851',
            },
            {
                title: '商业 - 创投 ',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/858.html'],
                target: '/jiemian/lists/858',
            },
            {
                title: '商业 - 能源',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/856.html'],
                target: '/jiemian/lists/856',
            },
            {
                title: '商业 - 数码',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/853.html'],
                target: '/jiemian/lists/853',
            },
            {
                title: '商业 - 教育',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/256.html'],
                target: '/jiemian/lists/256',
            },
            {
                title: '商业 - 食品',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/845.html'],
                target: '/jiemian/lists/845',
            },
            {
                title: '商业 - 新能源',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/857.html'],
                target: '/jiemian/lists/857',
            },
            {
                title: '商业 - 家电',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/850.html'],
                target: '/jiemian/lists/850',
            },
            {
                title: '商业 - 健康',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/854.html'],
                target: '/jiemian/lists/854',
            },
            {
                title: '商业 - 酒业',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/676.html'],
                target: '/jiemian/lists/676',
            },
            {
                title: '商业 - 物流',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/841.html'],
                target: '/jiemian/lists/841',
            },
            {
                title: '商业 - 零售',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/847.html'],
                target: '/jiemian/lists/847',
            },
            {
                title: '商业 - 美妆',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/838.html'],
                target: '/jiemian/lists/838',
            },
            {
                title: '商业 - 楼市',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/city/main/181.html'],
                target: '/jiemian/city/main/181',
            },
            {
                title: '商业 - 家居',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/694.html'],
                target: '/jiemian/lists/694',
            },
            {
                title: '商业 - 餐饮',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/848.html'],
                target: '/jiemian/lists/848',
            },
            {
                title: '商业 - 日用',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/846.html'],
                target: '/jiemian/lists/846',
            },
            {
                title: '商业 - 企服',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/852.html'],
                target: '/jiemian/lists/852',
            },
            {
                title: '商业 - 珠宝',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/839.html'],
                target: '/jiemian/lists/839',
            },
            {
                title: '商业 - 腕表',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/840.html'],
                target: '/jiemian/lists/840',
            },
            {
                title: '商业 - 商学院',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/605.html'],
                target: '/jiemian/lists/605',
            },
            {
                title: '商业 - 元宇宙',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/704.html'],
                target: '/jiemian/lists/704',
            },
            {
                title: '商业 - 电厂',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/872.html'],
                target: '/jiemian/lists/872',
            },
            {
                title: '商业 - 农业',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-shang-ye',
                source: ['/lists/883.html'],
                target: '/jiemian/lists/883',
            },
            {
                title: '财经 - 金融',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-cai-jing',
                source: ['/lists/9.html'],
                target: '/jiemian/lists/9',
            },
            {
                title: '财经 - 投资',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-cai-jing',
                source: ['/lists/86.html'],
                target: '/jiemian/lists/86',
            },
            {
                title: '财经 - 证券',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-cai-jing',
                source: ['/lists/112.html'],
                target: '/jiemian/lists/112',
            },
            {
                title: '财经 - IPO',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-cai-jing',
                source: ['/lists/699.html'],
                target: '/jiemian/lists/699',
            },
            {
                title: '财经 - 宏观',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-cai-jing',
                source: ['/lists/174.html'],
                target: '/jiemian/lists/174',
            },
            {
                title: '财经 - 股市',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-cai-jing',
                source: ['/lists/418.html'],
                target: '/jiemian/lists/418',
            },
            {
                title: '财经 - 财富',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-cai-jing',
                source: ['/lists/410.html'],
                target: '/jiemian/lists/410',
            },
            {
                title: '财经 - 有连云',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-cai-jing',
                source: ['/lists/889.html'],
                target: '/jiemian/lists/889',
            },
            {
                title: '新闻 - 天下',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/32.html'],
                target: '/jiemian/lists/32',
            },
            {
                title: '新闻 - 中国',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/71.html'],
                target: '/jiemian/lists/71',
            },
            {
                title: '新闻 - 地方',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/city/main/279.html'],
                target: '/jiemian/city/main/279',
            },
            {
                title: '新闻 - 评论',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/8.html'],
                target: '/jiemian/lists/8',
            },
            {
                title: '新闻 - 数据',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/154.html'],
                target: '/jiemian/lists/154',
            },
            {
                title: '新闻 - 职场',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/50.html'],
                target: '/jiemian/lists/50',
            },
            {
                title: '新闻 - 国是',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/422.html'],
                target: '/jiemian/lists/422',
            },
            {
                title: '新闻 - 体育',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/82.html'],
                target: '/jiemian/lists/82',
            },
            {
                title: '新闻 - 文娱',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/63.html'],
                target: '/jiemian/lists/63',
            },
            {
                title: '新闻 - 影像',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/225.html'],
                target: '/jiemian/lists/225',
            },
            {
                title: '新闻 - 营销',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/49.html'],
                target: '/jiemian/lists/49',
            },
            {
                title: '新闻 - 大湾区',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/680.html'],
                target: '/jiemian/lists/680',
            },
            {
                title: '新闻 - ESG',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/712.html'],
                target: '/jiemian/lists/712',
            },
            {
                title: '新闻 - 双碳',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/877.html'],
                target: '/jiemian/lists/877',
            },
            {
                title: '新闻 - 长三角',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-xin-wen',
                source: ['/lists/917.html'],
                target: '/jiemian/lists/917',
            },
            {
                title: '文化生活 - 文化',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-wen-hua-sheng-huo',
                source: ['/lists/130.html'],
                target: '/jiemian/lists/130',
            },
            {
                title: '文化生活 - 文旅',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-wen-hua-sheng-huo',
                source: ['/lists/105.html'],
                target: '/jiemian/lists/105',
            },
            {
                title: '文化生活 - 生活方式',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-wen-hua-sheng-huo',
                source: ['/lists/135.html'],
                target: '/jiemian/lists/135',
            },
            {
                title: '文化生活 - 美食美酒',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-wen-hua-sheng-huo',
                source: ['/lists/865.html'],
                target: '/jiemian/lists/865',
            },
            {
                title: '文化生活 - 艺术',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-wen-hua-sheng-huo',
                source: ['/lists/643.html'],
                target: '/jiemian/lists/643',
            },
            {
                title: '文化生活 - 游戏',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-wen-hua-sheng-huo',
                source: ['/lists/118.html'],
                target: '/jiemian/lists/118',
            },
            {
                title: '文化生活 - 正午',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-wen-hua-sheng-huo',
                source: ['/lists/53.html'],
                target: '/jiemian/lists/53',
            },
            {
                title: '文化生活 - 箭厂',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-wen-hua-sheng-huo',
                source: ['/video/lists/195_1.html'],
                target: '/jiemian/video/lists/195_1',
            },
            {
                title: '快报 - 今日热点',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-kuai-bao',
                source: ['/lists/1324kb.html'],
                target: '/jiemian/lists/1324kb',
            },
            {
                title: '快报 - 公司头条',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-kuai-bao',
                source: ['/lists/1322kb.html'],
                target: '/jiemian/lists/1322kb',
            },
            {
                title: '快报 - 股市前沿',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-kuai-bao',
                source: ['/lists/1327kb.html'],
                target: '/jiemian/lists/1327kb',
            },
            {
                title: '快报 - 监管通报',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-kuai-bao',
                source: ['/lists/1330kb.html'],
                target: '/jiemian/lists/1330kb',
            },
            {
                title: '快报 - 财经速览',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-kuai-bao',
                source: ['/lists/1326kb.html'],
                target: '/jiemian/lists/1326kb',
            },
            {
                title: '快报 - 时事追踪',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-lan-mu-kuai-bao',
                source: ['/lists/1325kb.html'],
                target: '/jiemian/lists/1325kb',
            },
            {
                title: 'VIP - 投资早晚报',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/12.html'],
                target: '/jiemian/pro/lists/12',
            },
            {
                title: 'VIP - 宏观晚6点',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/20.html'],
                target: '/jiemian/pro/lists/20',
            },
            {
                title: 'VIP - 打新早报',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/21.html'],
                target: '/jiemian/pro/lists/21',
            },
            {
                title: 'VIP - 盘前机会前瞻',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/13.html'],
                target: '/jiemian/pro/lists/13',
            },
            {
                title: 'VIP - 公告快评',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/14.html'],
                target: '/jiemian/pro/lists/14',
            },
            {
                title: 'VIP - 盘中必读',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/15.html'],
                target: '/jiemian/pro/lists/15',
            },
            {
                title: 'VIP - 金股挖掘',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/16.html'],
                target: '/jiemian/pro/lists/16',
            },
            {
                title: 'VIP - 调研早知道',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/17.html'],
                target: '/jiemian/pro/lists/17',
            },
            {
                title: 'VIP - 研报新知',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/18.html'],
                target: '/jiemian/pro/lists/18',
            },
            {
                title: 'VIP - 大势侦察',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/1.html'],
                target: '/jiemian/pro/lists/1',
            },
            {
                title: 'VIP - 市场风向标',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-vip',
                source: ['/pro/lists/19.html'],
                target: '/jiemian/pro/lists/19',
            },
            {
                title: '界面号 - 财经号',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-jie-mian-hao',
                source: ['/account/main/1.html'],
                target: '/jiemian/account/main/1',
            },
            {
                title: '界面号 - 城市号',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-jie-mian-hao',
                source: ['/account/main/2.html'],
                target: '/jiemian/account/main/2',
            },
            {
                title: '界面号 - 媒体号',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-jie-mian-hao',
                source: ['/account/main/3.html'],
                target: '/jiemian/account/main/3',
            },
            {
                title: '视频 - 界面Vnews',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-shi-pin',
                source: ['/video/lists/258_1.html'],
                target: '/jiemian/video/lists/258_1',
            },
            {
                title: '视频 - 直播',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-shi-pin',
                source: ['/videoLive/lists_1.html'],
                target: '/jiemian/videoLive/lists_1',
            },
            {
                title: '视频 - 箭厂',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-shi-pin',
                source: ['/video/lists/195_1.html'],
                target: '/jiemian/video/lists/195_1',
            },
            {
                title: '视频 - 面谈',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-shi-pin',
                source: ['/video/lists/111_1.html'],
                target: '/jiemian/video/lists/111_1',
            },
            {
                title: '视频 - 品牌创酷',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-shi-pin',
                source: ['/video/lists/226_1.html'],
                target: '/jiemian/video/lists/226_1',
            },
            {
                title: '视频 - 番茄社',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-shi-pin',
                source: ['/video/lists/567_1.html'],
                target: '/jiemian/video/lists/567_1',
            },
            {
                title: '视频 - 商业微史记',
                docs: 'https://docs.rsshub.app/routes/traditional-media#jie-mian-xin-wen-shi-pin',
                source: ['/video/lists/882_1.html'],
                target: '/jiemian/video/lists/882_1',
            },
        ],
    },
};
