# These are supported funding model platforms
github: DIYgod
open_collective: RSSHub
patreon: DIYgod
custom: ['https://afdian.net/@diygod', 'https://archive.diygod.me/images/zfb.jpg', 'https://archive.diygod.me/images/wx.jpg']
