# Vouched contributors for this project.
#
# See https://github.com/mitchellh/vouch for details.
#
# Syntax:
#   - One handle per line (without @), sorted alphabetically.
#   - Optional platform prefix: platform:username (e.g., github:user).
#   - Denounce with minus prefix: -username or -platform:username.
#   - Optional details after a space following the handle.
-an-lee impersonate as enpitsulin and DIYgod in #22205, 3a07e45a99c5300f47dadb2e91b40334626759d5. 2nd offense in #22929, b19ede356a535b36db10cbba3e8798045dc1a12e. 3rd offense in #22931, 41c4b80f7b57bbe13b2cc80eb98a54f4c6282668.
-betterandbetterii impersonate as dvorak0, goestav, Kjasn, Loongphy, TonyRL, ttttmr and xbot. https://github.com/DIYgod/RSSHub/commit/9e6f84df79bc9efcfabb0ca0768d7fded6775a1a.
diygod
henryqw
hyoban
neverbehave
pseudoyu
tonyrl
-weixshaw impersonate as magazian in #23333. 23f8a7a8509f6620a79503a45370a7339a157bcb
-zhangsan-xyz impersonate as TonyRL, cscnk52 in #22881. 6e51dceaf55678d0a24361dc1205d4a9e794435f
zhenlonghe
