image: gitpod/workspace-node-lts

ports:
  - name: app
    port: 1200
    onOpen: notify
    visibility: public
  - name: docs
    port: 3000
    onOpen: notify
    visibility: public

tasks:
  - name: deps
    before: |
      sudo apt update
      sudo apt install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libexpat1 libgbm1 libglib2.0-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 wget xdg-util
      sudo apt install -y redis-server
    init: pnpm i && pnpm i -C website && pnpm rb
  - name: app
    command: pnpm run dev
    openMode: tab-after
  # - name: docs
  #   command: |
  #     cd website
  #     pnpm run start
  #   openMode: tab-after
  - name: Restore Tailscale daemon
    command: |
      if [ -n "${TS_STATE_TAILSCALE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TS_STATE_TAILSCALE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled
  - name: Connect to Tailscale
    command: |
      if [ -n "${TS_STATE_TAILSCALE}" ]; then
        sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)" --authkey $TAILSCALE_AUTHKEY --accept-routes
      else
        sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)" --authkey $TAILSCALE_AUTHKEY --accept-routes
        # store the tailscale state into gitpod user
        gp env TS_STATE_TAILSCALE="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
      exit

vscode:
  extensions:
    - cweijan.vscode-database-client2@5.3.1 # you may need to rollback to v5.3.1 or below in **VS Code Desktop**
    - DavidAnson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - deepscan.vscode-deepscan
    - foxundermoon.shell-format
    - octref.vetur
    - rangav.vscode-thunder-client
    - sonarsource.sonarlint-vscode
    - vivaxy.vscode-conventional-commits
    - WakaTime.vscode-wakatime
    - yzhang.markdown-all-in-one
    # - ZihanLi.at-helper not available on Open VSX

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
