repos:
    - repo: local
      hooks:
          - id: format-description
            name: format-description
            entry: pnpm exec tsx scripts/workflow/format-description.ts
            language: system
            files: \.(ts|tsx|js|cjs|mjs)$
          - id: oxlint
            name: oxlint
            entry: pnpm exec oxlint --type-aware --fix
            language: system
            files: \.(ts|tsx|js|cjs|mjs)$
          - id: eslint
            name: eslint
            entry: pnpm exec eslint --cache --fix --concurrency auto
            language: system
            files: \.(ts|tsx|js|cjs|mjs|ya?ml)$
          - id: oxfmt
            name: oxfmt
            entry: pnpm exec oxfmt --no-error-on-unmatched-pattern
            language: system
          - id: typecheck
            name: typecheck
            entry: pnpm typecheck
            language: system
            pass_filenames: false
            always_run: true
