services:
  rsshub:
    # 核心变化：使用 build 指令代替 image 拉取
    build: .
    image: my-rsshub:v1  # 给你的专属镜像打个标签
    restart: always
    ports:
      - '1200:1200'
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data: