version: '3.8'
services:
    rsshub:
        image: franksun123/rsshub:latest
        container_name: rsshubfrank
        restart: always
        network_mode: host
        environment:
            - NODE_ENV=production
            - CACHE_TYPE=redis
            - REDIS_URL=redis://127.0.0.1:6379/0
            - FLARESOLVERR_URL=http://127.0.0.1:8191/v1
        depends_on:
            - redis

    redis:
        image: redis:alpine
        container_name: rsshub-redis
        restart: always
        network_mode: host
        volumes:
            - ./redis-data:/data
