services:
  - type: web
    name: rsshub
    env: node
    plan: hobby
    repo: https://github.com/MrPach/RSSHub
    branch: master
    buildCommand: 'NODE_OPTIONS="--max-old-space-size=1024" npm install && npm run build'
    startCommand: npm start
