services:
  - type: web
    name: rsshub
    env: node
    plan: free
    repo: https://github.com/MrPach/RSSHub
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=128
