export default {
    'jinse.cn': {
        _name: '金色财经',
        '.': [
            {
                title: '首页 - 头条',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/头条',
            },
            {
                title: '首页 - 独家',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/独家',
            },
            {
                title: '首页 - 铭文',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/铭文',
            },
            {
                title: '首页 - 产业',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/产业',
            },
            {
                title: '首页 - 项目',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/项目',
            },
            {
                title: '首页 - 政策',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/政策',
            },
            {
                title: '首页 - AI',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/AI',
            },
            {
                title: '首页 - Web 3.0',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/Web 3.0',
            },
            {
                title: '首页 - 以太坊2.0',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/以太坊2.0',
            },
            {
                title: '首页 - DeFi',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/DeFi',
            },
            {
                title: '首页 - Layer2',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/Layer2',
            },
            {
                title: '首页 - NFT',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/NFT',
            },
            {
                title: '首页 - DAO',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/DAO',
            },
            {
                title: '首页 - 百科',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-shou-ye',
                source: ['/'],
                target: '/jinse/timeline/百科',
            },
            {
                title: '快讯 - 全部',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-kuai-xun',
                source: ['/lives'],
                target: '/jinse/lives/0',
            },
            {
                title: '快讯 - 精选',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-kuai-xun',
                source: ['/lives'],
                target: '/jinse/lives/1',
            },
            {
                title: '快讯 - 政策',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-kuai-xun',
                source: ['/lives'],
                target: '/jinse/lives/2',
            },
            {
                title: '快讯 - 数据',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-kuai-xun',
                source: ['/lives'],
                target: '/jinse/lives/3',
            },
            {
                title: '快讯 - NFT',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-kuai-xun',
                source: ['/lives'],
                target: '/jinse/lives/4',
            },
            {
                title: '快讯 - 项目',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-kuai-xun',
                source: ['/lives'],
                target: '/jinse/lives/5',
            },
            {
                title: '分类 - 政策',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/zhengce',
            },
            {
                title: '分类 - 行情',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/fenxishishuo',
            },
            {
                title: '分类 - DeFi',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/defi',
            },
            {
                title: '分类 - 矿业',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/kuang',
            },
            {
                title: '分类 - 以太坊 2.0',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/以太坊2.0',
            },
            {
                title: '分类 - 产业',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/industry',
            },
            {
                title: '分类 - IPFS',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/IPFS',
            },
            {
                title: '分类 - 技术',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/tech',
            },
            {
                title: '分类 - 百科',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/baike',
            },
            {
                title: '分类 - 研报',
                docs: 'https://docs.rsshub.app/routes/finance#jin-se-cai-jing-fen-lei',
                source: ['/'],
                target: '/jinse/capitalmarket',
            },
        ],
    },
};
