module.exports = {
    de: {
        country: 'de',
        countryCN: '德国',
        link: 'http://de.chineseembassy.org/chn/lsfw/jqtz/',
        list: '#docMore a',
        title: '#article > table > tbody > tr:nth-child(2) b',
        description: '#article > table > tbody > tr:nth-child(10) > td > div',
        pubDate: '#article > table > tbody > tr:nth-child(6) > td',
    },
    jp: {
        country: 'jp',
        countryCN: '日本',
        link: 'http://jp.china-embassy.org/chn/lsfws/LSB/',
        list: '#docMore > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(2) > td > table:nth-child(3) a',
        title: '#article > tbody > tr:nth-child(1) > td > table > tbody > tr:nth-child(1) > td',
        description: '#article > tbody > tr:nth-child(2) > td',
        pubDate: '#article > tbody > tr:nth-child(1) > td > table > tbody > tr:nth-child(4) > td',
        consulates: {
            nagasaki: {
                cityCN: '长崎',
                link: 'http://nagasaki.china-consulate.org/chn/tzgg/',
                list: '.newsList a',
                title: '#News_Body_Title',
                description: '#News_Body_Txt_A',
                pubDate: '#News_Body_Time',
            },
            osaka: {
                cityCN: '大阪',
                link: 'http://osaka.china-consulate.org/chn/tzgg/',
                list: '#liebiao > tbody > tr > td:nth-child(1) > table:nth-child(3) > tbody a',
                title: '#article > tbody > tr:nth-child(1) > td > table > tbody > tr:nth-child(1) > td',
                description: '#article > tbody > tr:nth-child(3) > td',
                pubDate: '#article > tbody > tr:nth-child(2) > td',
            },
            fukuoka: {
                cityCN: '福冈',
                link: 'http://fukuoka.china-consulate.org/chn/tztg/',
                list: '#docMore > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(2) > td > table:nth-child(2) > tbody a',
                title: '#article > tbody > tr:nth-child(1) > td > table > tbody > tr:nth-child(1) > td',
                description: '#article > tbody > tr:nth-child(3) > td',
                pubDate: '#article > tbody > tr:nth-child(2) > td',
            },
            nagoya: {
                cityCN: '名古屋',
                link: 'http://nagoya.chineseconsulate.org/chn/gzgg/',
                list: '#docMore > div.mbox.fl > div > div.cbox_ul > ul a',
                title: '#News_Body_Title',
                description: '#News_Body_Txt_A',
                pubDate: '#News_Body_Time',
            },
            sapporo: {
                cityCN: '札幌',
                link: 'http://sapporo.china-consulate.org/chn/tzbg/',
                list: '#docMore > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(2) > td > table:nth-child(3) > tbody > tr:nth-child(1) a',
                title: '#article > tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(1) > td',
                description: '#article > tbody > tr > td > table:nth-child(2) > tbody > tr:nth-child(1) > td',
                pubDate: '#article > tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(4) > td',
            },
            niigata: {
                cityCN: '新潟',
                link: 'http://niigata.china-consulate.org/chn/lsbh/tztg/',
                list: '#docMore a',
                title: '#article > tbody > tr:nth-child(1) > td > table > tbody > tr:nth-child(4) > td',
                description: '#article > tbody > tr:nth-child(2) > td',
                pubDate: '#article > tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(4) > td',
            },
        },
    },
    kr: {
        country: 'kr',
        countryCN: '日本',
        link: 'http://jp.china-embassy.org/chn/lsfws/LSB/',
        list: '#docMore > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(2) > td > table:nth-child(3) a',
        title: '#article > tbody > tr:nth-child(1) > td > table > tbody > tr:nth-child(1) > td',
        description: '#article > tbody > tr:nth-child(2) > td',
        pubDate: '#article > tbody > tr:nth-child(1) > td > table > tbody > tr:nth-child(4) > td',
    },
    sg: {
        country: 'sg',
        countryCN: '新加坡',
        link: 'http://sg.china-embassy.org/chn/lsfw/zytzs/',
        list: '#docMore a',
        title: '#News_Body_Title',
        description: '#News_Body_Txt_A',
        pubDate: '#News_Body_Time',
    },
    uk: {
        country: 'uk',
        countryCN: '英国',
        link: 'http://www.chinese-embassy.org.uk/chn/lsfw/lsxz/txyxw/zxtg/',
        list: 'body > table:nth-child(6) > tbody > tr > td:nth-child(2) > table > tbody > tr > td > table > tbody > tr:nth-child(2) > td > table > tbody > tr:nth-child(2) a',
        title: '#article > tbody > tr:nth-child(2) > td',
        description: '#article .content',
        pubDate: '#article > tbody > tr:nth-child(5) > td',
        consulates: {
            belfast: {
                cityCN: '贝尔法斯特',
                link: 'http://belfast.chineseconsulate.org/chn/tztg/',
                list: 'div.newslist a',
                title: '#News_Body_Title',
                description: '#News_Body_Txt_A > div',
                pubDate: '#News_Body_Time',
            },
            edinburgh: {
                cityCN: '爱丁堡',
                link: 'http://edinburgh.china-consulate.org/chn/zytz/',
                list: '#TRS_OUTLINE > tbody > tr:nth-child(3) a',
                title: '#article > tbody > tr:nth-child(1) > td',
                description: '#article > tbody > tr:nth-child(3) > td',
                pubDate: '#article > tbody > tr:nth-child(2) > td',
            },
            manchester: {
                cityCN: '曼彻斯特',
                link: 'http://manchester.chineseconsulate.org/chn/tzgg/',
                list: 'div#TRS a',
                title: '#article > table > tbody > tr:nth-child(1) > td > font > b',
                description: '#article > table > tbody > tr:nth-child(6) > td > div > div',
                pubDate: '#article > table > tbody > tr:nth-child(4) > td > font',
            },
        },
    },
    us: {
        country: 'us',
        countryCN: '美国',
        link: 'http://www.china-embassy.org/chn/lszj/zytz/',
        list: 'div#docMore a',
        title: '#News_Body_Title',
        description: '#News_Body_Txt_A',
        pubDate: '#News_Body_Time > div:nth-child(1) > span',
        consulates: {
            chicago: {
                cityCN: '芝加哥',
                link: 'http://www.chinaconsulatechicago.org/chn/zytz/',
                list: 'div#TRS a',
                title: '#article > table > tbody > tr:nth-child(1) > td',
                description: '#article > table > tbody > tr:nth-child(6) > td > div',
                pubDate: '#article > table > tbody > tr:nth-child(3) > td > font',
            },
            newyork: {
                cityCN: '纽约',
                link: 'http://newyork.china-consulate.org/chn/fwzc/zxtz/',
                list: 'div.cbox_ul a',
                title: '#News_Body_Title',
                description: '#News_Body_Txt_A',
                pubDate: '#News_Body_Time',
            },
            sanfrancisco: {
                cityCN: '旧金山',
                link: 'http://www.chinaconsulatesf.org/chn/zytz/',
                list: 'div#docMore a',
                title: '#News_Body_Title',
                description: '#article > .News_Body_Txt_A',
                pubDate: '#News_Body_Time',
            },
        },
    },
};
