export default {
    // ministry
    '/cac/:path+': ['drgnchan'],
    '/caac/cjwt/:category?': ['nczitzk'],
    '/ccdi/:path+': ['bigfei'],
    '/chinamine-safety/zfxxgk/:category?': ['nczitzk'],
    '/chinamine-safety/xw/:category?': ['nczitzk'],
    '/chinatax/latest': ['nczitzk', 'fuzy112'],
    '/cmse/xwzx/zhxw': ['nczitzk'],
    '/cmse/xwzx/yzjz': ['nczitzk'],
    '/cmse/gfgg': ['nczitzk'],
    '/cmse/fxrw': ['nczitzk'],
    '/cmse/kjkx/:id': ['nczitzk'],
    '/cmse/gjhz': ['nczitzk'],
    '/cmse/hqsy/:id': ['nczitzk'],
    '/cmse/ztbd/:id': ['nczitzk'],
    '/cmse/kpjy/:id': ['nczitzk'],
    '/cmse/:path+': ['nczitzk'],
    '/cnnic/:path+': ['nczitzk'],
    '/csrc/auditstatus/:apply_id': ['hillerliao'],
    '/csrc/news/:suffix*': ['chinobing', 'LogicJake'],
    '/customs/list/:gchannel?': ['Jeason0228', 'TonyRL', 'he1q'],
    '/fmprc/:category?': ['nicolaszf', 'nczitzk'],
    '/forestry/gjlckjdjt/:category?': ['nczitzk'],
    '/immiau/news': ['liu233w'],
    '/jgjcndrc/:id?': ['nczitzk'],
    '/jinan/healthcommission/medical_exam_notice': ['tzjyxb'],
    '/mee/ywdt/:category?': ['liuxsdev'],
    '/mem/gk/sgcc/:category?': ['nczitzk'],
    '/mfa/wjdt/:category?': ['nczitzk'],
    '/miit/wjfb/:ministry': ['Fatpandac'],
    '/miit/yjzj': ['Fatpandac'],
    '/miit/zcwj': ['Yoge-Code'],
    '/miit/wjgs': ['Yoge-Code'],
    '/miit/zcjd': ['Yoge-Code'],
    '/moa/zdscxx/:channel?/:source?': ['MisteryMonster', 'nczitzk'],
    '/moa/:suburl': ['Origami404'],
    '/moe/:type': ['Crawler995'],
    '/moe/s78/:column': ['TonyRL'],
    '/mof/bond/:category?': ['la3rence'],
    '/mofcom/article/:suffix+': ['LogicJake'],
    '/moj/aac/news/:type?': ['TonyRL'],
    '/moj/lfyjzj': ['la3rence'],
    '/mot/:category?': ['nczitzk'],
    '/ndrc/fggz/:category?': ['nczitzk'],
    '/ndrc/xwdt/:category?': ['nczitzk'],
    '/nea/sjzz/ghs': ['nczitzk'],
    '/news/:uid': ['EsuRt'],
    '/nifdc/:path?': ['nczitzk'],
    '/nmpa/:path+': ['TonyRL'],
    '/nopss/:path+': ['nczitzk'],
    '/npc/:caty': ['233yeee'],
    '/nrta/news/:category?': ['yuxinliu-alex'],
    '/nrta/dsj/:category?': ['nczitzk'],
    '/nsfc/news/:type?': ['Derekmini', 'nczitzk'],
    '/pbc/goutongjiaoliu': ['nczitzk'],
    '/pbc/gzlw': ['Fatpandac'],
    '/pbc/tradeAnnouncement': ['nczitzk'],
    '/pbc/zcyj': ['Fatpandac'],
    '/samr/xgzlyhd/:category?/:department?': ['nczitzk'],
    '/safe/business/:site?': ['nczitzk'],
    '/safe/complaint/:site?': ['nczitzk'],
    '/sasac/:path+': ['TonyRL'],
    '/stats/:path+': ['bigfei', 'nczitzk'],
    '/zhengce/govall/:advance?': ['ciaranchen'],
    '/zhengce/wenjian/:pcodeJiguan?': ['ciaranchen'],
    '/zhengce/zhengceku/:department': ['zxx-457'],
    '/zhengce/zuixin': ['SettingDust', 'nczitzk'],
    '/zhengce/:category?': ['nczitzk'],
    // province
    '/anhui/kjt/:path?': ['nczitzk'],
    '/beijing/bjedu/gh/:urlPath?': ['TonyRL'],
    '/beijing/bphc/:channel': ['bigfei'],
    '/beijing/jw/tzgg': ['nczitzk'],
    '/beijing/kw/:channel': ['Fatpandac'],
    '/chongqing/gzw/:category?': ['nczitzk'],
    '/chongqing/rsks': ['Mai19930513'],
    '/chongqing/sydwgkzp': ['MajexH'],
    '/dianbai/:path+': ['ShuiHuo'],
    '/gaozhou/:path+': ['ShuiHuo'],
    '/guangdong/tqyb/sncsyjxh': ['Fatpandac'],
    '/guangdong/tqyb/tfxtq': ['Fatpandac'],
    '/gz/xw/:category': ['drgnchan'],
    '/gz/zwgk/:category': ['drgnchan'],
    '/hebei/czt/xwdt/:category?': ['nczitzk'],
    '/huazhou/:path+': ['ShuiHuo'],
    '/huizhou/zwgk/:category?': ['Fatpandac'],
    '/hunan/changsha/major-email': ['shansing'],
    '/maoming/:path+': ['ShuiHuo'],
    '/maonan/:category': ['ShuiHuo'],
    '/mgs/:path+': ['ShuiHuo'],
    '/mmht/:path+': ['ShuiHuo'],
    '/sdb/:path+': ['ShuiHuo'],
    '/shaanxi/kjt/:id?': ['nczitzk'],
    '/shanghai/rsj/ksxm': ['Fatpandac'],
    '/shanghai/wsjkw/yqtb': ['zcf0508'],
    '/shanghai/yjj/:path+': ['nczitzk'],
    '/shanghai/wgj/:page?': ['gideonsenku'],
    '/shenzhen/hrss/szksy/:caty/:page?': ['zlasd'],
    '/shenzhen/xxgk/zfxxgj/:caty': ['laoxua'],
    '/shenzhen/zjj/xxgk/:caty': ['lonn'],
    '/shenzhen/zzb/:caty/:page?': ['zlasd'],
    '/sichuan/deyang/govpublicinfo/:countyName/:infoType?': ['zytomorrow'],
    '/sichuan/deyang/mztoday/:infoType?': ['zytomorrow'],
    '/suzhou/doc': ['EsuRt'],
    '/suzhou/fg/:category?': ['nczitzk'],
    '/suzhou/news/:uid': ['EsuRt', 'luyuhuang'],
    '/taiyuan/rsj/:caty/:page?': ['2PoL'],
    '/wuhan/sy/whyw': ['nczitzk'],
    '/xinyi/:path+': ['ShuiHuo'],
    '/xuzhou/hrss/:category?': ['nczitzk'],
    '/zhejiang/gwy/:category?/:column?': ['nczitzk'],
};
