/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "RSSHub",
  "tagline": "🍰 Everything is RSSible",
  "favicon": "img/logo.png",
  "url": "https://docs.rsshub.app",
  "baseUrl": "/zh/",
  "organizationName": "DIYgod",
  "projectName": "RSSHub",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "zh",
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "mermaid": false
  },
  "plugins": [
    [
      "@dipakparmar/docusaurus-plugin-umami",
      {
        "websiteID": "be1761be-7547-49d5-91b8-5c97c8f7cec7",
        "analyticsDomain": "umami.diygod.dev"
      }
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {
        "fromExtensions": [
          "html"
        ],
        "redirects": [
          {
            "from": "/joinus",
            "to": "/joinus/quick-start"
          },
          {
            "from": "/joinus/script-standard",
            "to": "/joinus/advanced/script-standard"
          },
          {
            "from": "/joinus/pub-date",
            "to": "/joinus/advanced/pub-date"
          },
          {
            "from": "/joinus/use-cache",
            "to": "/joinus/advanced/use-cache"
          },
          {
            "from": [
              "/social-media",
              "/en/social-media"
            ],
            "to": "/routes/social-media"
          },
          {
            "from": [
              "/new-media",
              "/en/new-media"
            ],
            "to": "/routes/new-media"
          },
          {
            "from": [
              "/traditional-media",
              "/en/traditional-media"
            ],
            "to": "/routes/traditional-media"
          },
          {
            "from": [
              "/bbs",
              "/en/bbs"
            ],
            "to": "/routes/bbs"
          },
          {
            "from": [
              "/blog",
              "/en/blog"
            ],
            "to": "/routes/blog"
          },
          {
            "from": [
              "/programming",
              "/en/programming"
            ],
            "to": "/routes/programming"
          },
          {
            "from": [
              "/design",
              "/en/design"
            ],
            "to": "/routes/design"
          },
          {
            "from": [
              "/live",
              "/en/live"
            ],
            "to": "/routes/live"
          },
          {
            "from": [
              "/multimedia",
              "/en/multimedia"
            ],
            "to": "/routes/multimedia"
          },
          {
            "from": [
              "/picture",
              "/en/picture"
            ],
            "to": "/routes/picture"
          },
          {
            "from": [
              "/anime",
              "/en/anime"
            ],
            "to": "/routes/anime"
          },
          {
            "from": [
              "/program-update",
              "/en/program-update"
            ],
            "to": "/routes/program-update"
          },
          {
            "from": [
              "/university",
              "/en/university"
            ],
            "to": "/routes/university"
          },
          {
            "from": [
              "/forecast",
              "/en/forecast"
            ],
            "to": "/routes/forecast"
          },
          {
            "from": [
              "/travel",
              "/en/travel"
            ],
            "to": "/routes/travel"
          },
          {
            "from": [
              "/shopping",
              "/en/shopping"
            ],
            "to": "/routes/shopping"
          },
          {
            "from": [
              "/game",
              "/en/game"
            ],
            "to": "/routes/game"
          },
          {
            "from": [
              "/reading",
              "/en/reading"
            ],
            "to": "/routes/reading"
          },
          {
            "from": [
              "/government",
              "/en/government"
            ],
            "to": "/routes/government"
          },
          {
            "from": [
              "/study",
              "/en/study"
            ],
            "to": "/routes/study"
          },
          {
            "from": [
              "/journal",
              "/en/journal"
            ],
            "to": "/routes/journal"
          },
          {
            "from": [
              "/finance",
              "/en/finance"
            ],
            "to": "/routes/finance"
          },
          {
            "from": [
              "/other",
              "/en/other"
            ],
            "to": "/routes/other"
          }
        ]
      }
    ],
    [
      "@docusaurus/plugin-pwa",
      {
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "/img/logo.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "#ffffff"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-capable",
            "content": "yes"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-status-bar-style",
            "content": "black-translucent"
          },
          {
            "tagName": "link",
            "rel": "apple-touch-icon",
            "href": "/img/apple-touch-icon.png"
          },
          {
            "tagName": "link",
            "rel": "mask-icon",
            "href": "/img/safari-pinned-tab.svg",
            "color": "#F5712C"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileImage",
            "content": "/img/logo.png"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileColor",
            "content": "#ffffff"
          }
        ]
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.mjs",
          "editUrl": "https://github.com/DIYgod/RSSHub/blob/master/website/",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-322PG1X4EL"
        }
      }
    ]
  ],
  "customFields": {
    "meilisearch-docsearch": {
      "host": "https://meilisearch.rsshub.app",
      "apiKey": "375c36cd9573a2c1d1e536214158c37120fdd0ba6cd8829f7a848e940cc22245",
      "indexUid": "rsshub",
      "container": "#docsearch"
    }
  },
  "themeConfig": {
    "image": "img/logo.png",
    "metadata": [
      {
        "name": "description",
        "content": "🍰 Everything is RSSible"
      }
    ],
    "navbar": {
      "title": "RSSHub",
      "logo": {
        "alt": "RSSHub",
        "src": "img/logo.png"
      },
      "items": [
        {
          "to": "/",
          "position": "left",
          "label": "指南",
          "activeBaseRegex": "^/(usage|instances|faq|parameter|api)?$"
        },
        {
          "to": "/routes",
          "position": "left",
          "label": "路由",
          "activeBaseRegex": "^/routes/"
        },
        {
          "to": "/joinus/quick-start",
          "label": "参与我们",
          "position": "left",
          "activeBaseRegex": "^/joinus/"
        },
        {
          "to": "/install",
          "position": "left",
          "label": "部署"
        },
        {
          "to": "/support",
          "position": "left",
          "label": "支持 RSSHub"
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/DIYgod/RSSHub",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "指南",
              "to": "/"
            },
            {
              "to": "/joinus/quick-start",
              "label": "参与我们"
            },
            {
              "to": "/install",
              "label": "部署"
            },
            {
              "to": "/support",
              "label": "支持 RSSHub"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/DIYgod/RSSHub"
            },
            {
              "label": "Telegram Group",
              "href": "https://t.me/rsshub"
            },
            {
              "label": "Telegram Channel",
              "href": "https://t.me/awesomeRSSHub"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/intent/follow?screen_name=_RSSHub"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "关于作者 DIYgod",
              "to": "https://diygod.cc"
            },
            {
              "label": "RSSHub Radar - 快速发现和订阅 RSS",
              "href": "https://github.com/DIYgod/RSSHub-Radar"
            },
            {
              "label": "xLog - 书写在区块链上的开源创作社区",
              "href": "https://xlog.app"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 RSSHub."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
