import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
    {
        path: '/zh/__docusaurus/debug',
        component: ComponentCreator('/zh/__docusaurus/debug', '75a'),
        exact: true,
    },
    {
        path: '/zh/__docusaurus/debug/config',
        component: ComponentCreator('/zh/__docusaurus/debug/config', 'cd2'),
        exact: true,
    },
    {
        path: '/zh/__docusaurus/debug/content',
        component: ComponentCreator('/zh/__docusaurus/debug/content', '311'),
        exact: true,
    },
    {
        path: '/zh/__docusaurus/debug/globalData',
        component: ComponentCreator('/zh/__docusaurus/debug/globalData', '932'),
        exact: true,
    },
    {
        path: '/zh/__docusaurus/debug/metadata',
        component: ComponentCreator('/zh/__docusaurus/debug/metadata', 'a59'),
        exact: true,
    },
    {
        path: '/zh/__docusaurus/debug/registry',
        component: ComponentCreator('/zh/__docusaurus/debug/registry', 'edf'),
        exact: true,
    },
    {
        path: '/zh/__docusaurus/debug/routes',
        component: ComponentCreator('/zh/__docusaurus/debug/routes', 'b22'),
        exact: true,
    },
    {
        path: '/zh/',
        component: ComponentCreator('/zh/', 'f6e'),
        routes: [
            {
                path: '/zh/',
                component: ComponentCreator('/zh/', '504'),
                routes: [
                    {
                        path: '/zh/',
                        component: ComponentCreator('/zh/', '0f7'),
                        routes: [
                            {
                                path: '/zh/api',
                                component: ComponentCreator('/zh/api', '421'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/faq',
                                component: ComponentCreator('/zh/faq', 'f84'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/install/',
                                component: ComponentCreator('/zh/install/', 'd5a'),
                                exact: true,
                                sidebar: 'installSidebar',
                            },
                            {
                                path: '/zh/install/config',
                                component: ComponentCreator('/zh/install/config', '5c2'),
                                exact: true,
                                sidebar: 'installSidebar',
                            },
                            {
                                path: '/zh/instances',
                                component: ComponentCreator('/zh/instances', '4ce'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/joinus/advanced/advanced-feed',
                                component: ComponentCreator('/zh/joinus/advanced/advanced-feed', '33f'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/advanced/debug',
                                component: ComponentCreator('/zh/joinus/advanced/debug', '7d5'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/advanced/pub-date',
                                component: ComponentCreator('/zh/joinus/advanced/pub-date', 'b2c'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/advanced/script-standard',
                                component: ComponentCreator('/zh/joinus/advanced/script-standard', '06b'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/advanced/use-cache',
                                component: ComponentCreator('/zh/joinus/advanced/use-cache', 'f06'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/new-radar',
                                component: ComponentCreator('/zh/joinus/new-radar', 'f77'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/new-rss/add-docs',
                                component: ComponentCreator('/zh/joinus/new-rss/add-docs', '12f'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/new-rss/before-start',
                                component: ComponentCreator('/zh/joinus/new-rss/before-start', '7bd'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/new-rss/prerequisites',
                                component: ComponentCreator('/zh/joinus/new-rss/prerequisites', 'b13'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/new-rss/start-code',
                                component: ComponentCreator('/zh/joinus/new-rss/start-code', 'dc1'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/new-rss/submit-route',
                                component: ComponentCreator('/zh/joinus/new-rss/submit-route', '027'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/joinus/quick-start',
                                component: ComponentCreator('/zh/joinus/quick-start', '347'),
                                exact: true,
                                sidebar: 'joinusSidebar',
                            },
                            {
                                path: '/zh/parameter',
                                component: ComponentCreator('/zh/parameter', '10c'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes',
                                component: ComponentCreator('/zh/routes', '997'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/anime',
                                component: ComponentCreator('/zh/routes/anime', '96a'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/bbs',
                                component: ComponentCreator('/zh/routes/bbs', '15b'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/blog',
                                component: ComponentCreator('/zh/routes/blog', '171'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/design',
                                component: ComponentCreator('/zh/routes/design', 'c45'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/finance',
                                component: ComponentCreator('/zh/routes/finance', '88a'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/forecast',
                                component: ComponentCreator('/zh/routes/forecast', 'f57'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/game',
                                component: ComponentCreator('/zh/routes/game', 'ccf'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/government',
                                component: ComponentCreator('/zh/routes/government', '77e'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/journal',
                                component: ComponentCreator('/zh/routes/journal', '0ea'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/live',
                                component: ComponentCreator('/zh/routes/live', '619'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/multimedia',
                                component: ComponentCreator('/zh/routes/multimedia', 'a0c'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/new-media',
                                component: ComponentCreator('/zh/routes/new-media', '985'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/other',
                                component: ComponentCreator('/zh/routes/other', '459'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/picture',
                                component: ComponentCreator('/zh/routes/picture', '745'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/program-update',
                                component: ComponentCreator('/zh/routes/program-update', '474'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/programming',
                                component: ComponentCreator('/zh/routes/programming', '261'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/reading',
                                component: ComponentCreator('/zh/routes/reading', '8be'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/shopping',
                                component: ComponentCreator('/zh/routes/shopping', '3fb'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/social-media',
                                component: ComponentCreator('/zh/routes/social-media', '8a8'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/study',
                                component: ComponentCreator('/zh/routes/study', '384'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/traditional-media',
                                component: ComponentCreator('/zh/routes/traditional-media', 'd53'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/travel',
                                component: ComponentCreator('/zh/routes/travel', 'ca0'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/routes/university',
                                component: ComponentCreator('/zh/routes/university', 'bfe'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/support/',
                                component: ComponentCreator('/zh/support/', '83d'),
                                exact: true,
                                sidebar: 'supportSidebar',
                            },
                            {
                                path: '/zh/usage',
                                component: ComponentCreator('/zh/usage', '61f'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                            {
                                path: '/zh/',
                                component: ComponentCreator('/zh/', '888'),
                                exact: true,
                                sidebar: 'guideSidebar',
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        path: '*',
        component: ComponentCreator('*'),
    },
];
