export default {
    '/dutdice/:category?': ['beautyyuyanli', 'nczitzk'],
    '/eda/:category?': ['nczitzk'],
    '/fldpj/:category?': ['ueiu'],
    '/gs/:category?': ['nczitzk'],
    '/news/:category?': ['nczitzk'],
    '/panjin/:category?': ['nczitzk'],
    '/perdep/:category?': ['nczitzk'],
    '/pjteach/:category?': ['nczitzk'],
    '/pjxqzwb/:category?': ['nczitzk'],
    '/ssdut/:category?': ['nczitzk'],
    '/teach/:category?': ['beautyyuyanli', 'nczitzk'],
    '/tycgzx/:category?': ['beatyyuyanli', 'nczitzk'],
    '/xsgzb/:category?': ['nczitzk'],
};
