module.exports = {
    '/bookstore/newest': ['xyqfer'],
    '/collection/:id/:getAll?': ['huruji', 'Colin-XKL', 'Fatpandac'],
    '/daily': ['DHPO'],
    '/daily/section/:sectionId': ['ccbikai'],
    '/hot/:category?': ['nczitzk'],
    '/hotlist': ['DIYgod'],
    '/people/activities/:id': ['DIYgod'],
    '/people/answers/:id': ['DIYgod', 'prnake'],
    '/people/pins/:id': ['xyqfer'],
    '/pin/daily': ['xyqfer'],
    '/pin/hotlist': ['xyqfer'],
    '/posts/:usertype/:id': ['whtsky', 'Colin-XKL'],
    '/question/:questionId': ['xyqfer', 'hacklu'],
    '/timeline': ['SeanChao'],
    '/topic/:topicId': ['xyqfer'],
    '/weekly': ['LogicJake'],
    '/zhuanlan/:id': ['DIYgod'],
};
