export default {
    'ncc-cma.net': {
        _name: '国家气候中心',
        cmdp: [
            {
                title: '中国气温 - 日平均气温距平',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/RPJQWQYZ',
            },
            {
                title: '中国气温 - 近5天平均气温距平',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ5TPJQWJP',
            },
            {
                title: '中国气温 - 近10天平均气温距平',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ10TQWJP',
            },
            {
                title: '中国气温 - 近20天平均气温距平',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ20TQWJP',
            },
            {
                title: '中国气温 - 近30天平均气温距平',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ30TQWJP',
            },
            {
                title: '中国气温 - 本月以来气温距平',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/BYYLQWJP',
            },
            {
                title: '中国气温 - 本季以来气温距平',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/BJYLQWJP',
            },
            {
                title: '中国气温 - 本年以来气温距平',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/BNYLQWJP',
            },
            {
                title: '中国降水 - 日降水量分布',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/QGRJSLFBT0808S',
            },
            {
                title: '中国降水 - 近5天降水量',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ5TJSLFBT',
            },
            {
                title: '中国降水 - 近10天降水量',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ10TJSL',
            },
            {
                title: '中国降水 - 近20天降水量',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ20TJSL',
            },
            {
                title: '中国降水 - 近30天降水量',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ30TJSL',
            },
            {
                title: '中国降水 - 本月以来降水量',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/BYYLJSL',
            },
            {
                title: '中国降水 - 本季以来降水量',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/BJYLJSL',
            },
            {
                title: '中国降水 - 近10天降水量距平百分率',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ10TJSLJP',
            },
            {
                title: '中国降水 - 近20天降水量距平百分率',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ20TJSLJP',
            },
            {
                title: '中国降水 - 近30天降水量距平百分率',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/ZJ30TJSLJP',
            },
            {
                title: '中国降水 - 本月以来降水量距平百分率',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/BYYLJSLJPZYQHZ',
            },
            {
                title: '中国降水 - 本季以来降水量距平百分率',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/BJYLJSLJPZJQHZ',
            },
            {
                title: '中国降水 - 本年以来降水量距平百分率',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/BNYLJSLJP',
            },
            {
                title: '全球气温 - 气温距平（最近10天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbtmeana10_',
            },
            {
                title: '全球气温 - 气温距平（最近20天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbtmeana20_',
            },
            {
                title: '全球气温 - 气温距平（最近30天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbtmeana30_',
            },
            {
                title: '全球气温 - 气温距平（最近90天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbtmeana90_',
            },
            {
                title: '全球气温 - 最低气温距平（最近30天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbtmina30_',
            },
            {
                title: '全球气温 - 最低气温距平（最近90天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbtmina90_',
            },
            {
                title: '全球气温 - 最高气温距平（最近30天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbtmaxa30_',
            },
            {
                title: '全球气温 - 最高气温距平（最近90天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbtmaxa90_',
            },
            {
                title: '全球降水 - 降水量（最近10天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbrain10_',
            },
            {
                title: '全球降水 - 降水量（最近20天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbrain20_',
            },
            {
                title: '全球降水 - 降水量（最近30天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbrain30_',
            },
            {
                title: '全球降水 - 降水量（最近90天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbrain90_',
            },
            {
                title: '全球降水 - 降水距平百分率（最近10天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbraina10_',
            },
            {
                title: '全球降水 - 降水距平百分率（最近20天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbraina20_',
            },
            {
                title: '全球降水 - 降水距平百分率（最近30天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbraina30_',
            },
            {
                title: '全球降水 - 降水距平百分率（最近90天）',
                docs: 'https://docs.rsshub.app/routes/forecast#guo-jia-qi-hou-zhong-xin-zui-xin-jian-ce',
                source: ['/cn/index.htm'],
                target: '/ncc-cma/cmdp/image/glbraina90_',
            },
        ],
    },
};
