module.exports = {
    '/51cto': ['cnkmmk'],
    '/51cto/?': ['cnkmmk'],
    '/zhujiceping': ['cnkmmk'],
    '/bulianglincom': ['cnkmmk'],
    '/diannaowanwu': ['cnkmmk'],
    '/freecomtw': ['cnkmmk'],
    '/hicairocom': ['cnkmmk'],
    '/howtoforge': ['cnkmmk'],
    '/iweeccom': ['cnkmmk'],
    '/lalaim': ['cnkmmk'],
    '/pcrookie': ['cnkmmk'],
    '/ruanjianyingyong': ['cnkmmk'],
    '/ygkkk': ['cnkmmk'],
    '/walixzcom': ['cnkmmk'],
    '/pianyivps': ['cnkmmk'],
    '/dongvpscom': ['cnkmmk'],
    '/freeadaycom': ['cnkmmk'],
    '/ippatop': ['cnkmmk'],
};
