export default {
    '/announce': ['xyqfer'],
    '/ce/:id': ['HenryQW'],
    '/ershicimi/:id': ['sanmmm'],
    '/data258/:id?': ['Rongronggg9'],
    '/feeddd/:id': ['TonyRL', 'Rongronggg9'],
    '/feeds': ['tylinux'],
    '/mp/homepage/:biz/:hid/:cid?': ['MisteryMonster'],
    '/mp/msgalbum/:biz/:aid': ['MisteryMonster'],
    '/sogou/:id': ['EthanWng97'],
    '/tgchannel/:id/:mpName?/:searchQueryType?': ['LogicJake', 'Rongronggg9'],
    '/uread/:userid': ['kt286'],
    '/wechat2rss/:id': ['TonyRL'],
    '/wxnmh/:id': ['laampui'],
};
