export default {
    'kantarworldpanel.com': {
        _name: 'Kantar Worldpanel',
        '.': [
            {
                title: 'News Centre China Eng - News',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/cn-en/news'],
                target: '/kantarworldpanel/cn-en/news',
            },
            {
                title: 'News Centre China Eng - Retail Snapshot',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/cn-en/publications'],
                target: '/kantarworldpanel/cn-en/publications',
            },
            {
                title: 'News Centre China Eng - Publications',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/cn-en/publications/Reports'],
                target: '/kantarworldpanel/cn-en/publications/Reports',
            },
            {
                title: 'News Centre China Eng - In the media',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/cn-en/In-the-media'],
                target: '/kantarworldpanel/cn-en/In-the-media',
            },
            {
                title: 'News Centre China 中文 - 新闻发布',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/cn/news'],
                target: '/kantarworldpanel/cn/news',
            },
            {
                title: 'News Centre China 中文 - 零售市场快报',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/cn/publications'],
                target: '/kantarworldpanel/cn/publications',
            },
            {
                title: 'News Centre China 中文 - 市场报告',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/cn/publications/China-Insights'],
                target: '/kantarworldpanel/cn/publications/China-Insights',
            },
            {
                title: 'News Centre China 中文 - 媒体报道',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/cn/press-releases'],
                target: '/kantarworldpanel/cn/press-releases',
            },
            {
                title: 'News Centre Indonesia - News',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/id/News'],
                target: '/kantarworldpanel/id/News',
            },
            {
                title: 'News Centre Indonesia - Kantar Scoop',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/id/News/Kantar-Worldpanel-Series'],
                target: '/kantarworldpanel/id/News/Kantar-Worldpanel-Series',
            },
            {
                title: 'News Centre Indonesia - Video Series',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/id/News/video-series'],
                target: '/kantarworldpanel/id/News/video-series',
            },
            {
                title: 'News Centre Indonesia - Podcast',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/id/News/podcast'],
                target: '/kantarworldpanel/id/News/podcast',
            },
            {
                title: 'News Centre Indonesia - Ready, Steady, Shop!',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/id/News/asia-shopper-series'],
                target: '/kantarworldpanel/id/News/asia-shopper-series',
            },
            {
                title: 'News Centre Indonesia - Asia Pulse',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/id/News/Asia-Pulse'],
                target: '/kantarworldpanel/id/News/Asia-Pulse',
            },
            {
                title: 'News Centre Korea - News',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/kr/news'],
                target: '/kantarworldpanel/kr/news',
            },
            {
                title: 'News Centre Korea - Insight Reports',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/kr/publications'],
                target: '/kantarworldpanel/kr/publications',
            },
            {
                title: 'News Centre Korea - In the Media',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/kr/press-releases'],
                target: '/kantarworldpanel/kr/press-releases',
            },
            {
                title: 'News Centre Malaysia - News',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/my/news'],
                target: '/kantarworldpanel/my/news',
            },
            {
                title: 'News Centre Philippines - Latest Insights',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/ph/Latest-Insights'],
                target: '/kantarworldpanel/ph/Latest-Insights',
            },
            {
                title: 'News Centre Philippines - In the Media',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/ph/In-the-Media'],
                target: '/kantarworldpanel/ph/In-the-Media',
            },
            {
                title: 'News Centre Philippines - Events',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/ph/events'],
                target: '/kantarworldpanel/ph/events',
            },
            {
                title: 'News Centre Taiwan - 聚焦台灣',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/ph/news/spotlight-on-taiwan'],
                target: '/kantarworldpanel/tw/news/spotlight-on-taiwan',
            },
            {
                title: 'News Centre Taiwan - WOW SPOT',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/tw/news/wowspot'],
                target: '/kantarworldpanel/tw/news/wowspot',
            },
            {
                title: 'News Centre Taiwan - 市場報告',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/tw/publications'],
                target: '/kantarworldpanel/tw/publications',
            },
            {
                title: 'News Centre Taiwan - 媒體報導',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/tw/press-releases'],
                target: '/kantarworldpanel/tw/press-releases',
            },
            {
                title: 'News Centre Taiwan - 活動',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/tw/events'],
                target: '/kantarworldpanel/tw/events',
            },
            {
                title: 'News Centre Thailand - News',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/th/news'],
                target: '/kantarworldpanel/th/news',
            },
            {
                title: 'News Centre Vietnam - Insights',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/vn/news'],
                target: '/kantarworldpanel/vn/news',
            },
            {
                title: 'News Centre Vietnam - FMCG Monitor',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/vn/news/FMCG-Monitor'],
                target: '/kantarworldpanel/vn/news/FMCG-Monitor',
            },
            {
                title: 'News Centre Vietnam - Ready, Steady, Shop!',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/vn/news/ready-steady-shop'],
                target: '/kantarworldpanel/vn/news/ready-steady-shop',
            },
            {
                title: 'News Centre Vietnam - Asia Pulse',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/vn/news/asia-pulse'],
                target: '/kantarworldpanel/vn/news/asia-pulse',
            },
            {
                title: 'News Centre Vietnam - IN THE MEDIA',
                docs: 'https://docs.rsshub.app/routes/new-media#kanta-worldpanel-news-centre',
                source: ['/vn/In-the-media'],
                target: '/kantarworldpanel/vn/In-the-media',
            },
        ],
    },
};
