module.exports = {
    '/ustb/news/adma': ['DA1Y1'],
    '/ustb/news/all': ['DA1Y1'],
    '/ustb/news/cicst': ['DA1Y1'],
    '/ustb/news/cres': ['DA1Y1'],
    '/ustb/news/huasheng': ['DA1Y1'],
    '/ustb/news/iet': ['DA1Y1'],
    '/ustb/news/ihmm': ['DA1Y1'],
    '/ustb/news/marx': ['DA1Y1'],
    '/ustb/news/me': ['DA1Y1'],
    '/ustb/news/metall': ['DA1Y1'],
    '/ustb/news/mse': ['DA1Y1'],
    '/ustb/news/ncms': ['DA1Y1'],
    '/ustb/news/saee': ['DA1Y1'],
    '/ustb/news/scce': ['DA1Y1'],
    '/ustb/news/sd': ['DA1Y1'],
    '/ustb/news/seee': ['DA1Y1'],
    '/ustb/news/sem': ['DA1Y1'],
    '/ustb/news/sfs': ['DA1Y1'],
    '/ustb/news/shuli': ['DA1Y1'],
    '/ustb/news/skl': ['DA1Y1'],
    '/ustb/news/slam': ['DA1Y1'],
    '/ustb/news/wenfa': ['DA1Y1'],
};
