module.exports = {
    '/yjsy/news/adma': ['DA1Y1'],
    '/yjsy/news/all': ['DA1Y1'],
    '/yjsy/news/cicst': ['DA1Y1'],
    '/yjsy/news/cres': ['DA1Y1'],
    '/yjsy/news/huasheng': ['DA1Y1'],
    '/yjsy/news/iet': ['DA1Y1'],
    '/yjsy/news/ihmm': ['DA1Y1'],
    '/yjsy/news/marx': ['DA1Y1'],
    '/yjsy/news/me': ['DA1Y1'],
    '/yjsy/news/metall': ['DA1Y1'],
    '/yjsy/news/mse': ['DA1Y1'],
    '/yjsy/news/ncms': ['DA1Y1'],
    '/yjsy/news/saee': ['DA1Y1'],
    '/yjsy/news/scce': ['DA1Y1'],
    '/yjsy/news/sd': ['DA1Y1'],
    '/yjsy/news/seee': ['DA1Y1'],
    '/yjsy/news/sem': ['DA1Y1'],
    '/yjsy/news/sfs': ['DA1Y1'],
    '/yjsy/news/shuli': ['DA1Y1'],
    '/yjsy/news/skl': ['DA1Y1'],
    '/yjsy/news/slam': ['DA1Y1'],
    '/yjsy/news/wenfa': ['DA1Y1'],
};
