module.exports = {
    '/news/adma': ['DA1Y1'],
    '/news/all': ['DA1Y1'],
    '/news/cicst': ['DA1Y1'],
    '/news/cres': ['DA1Y1'],
    '/news/huasheng': ['DA1Y1'],
    '/news/iet': ['DA1Y1'],
    '/news/ihmm': ['DA1Y1'],
    '/news/marx': ['DA1Y1'],
    '/news/me': ['DA1Y1'],
    '/news/metall': ['DA1Y1'],
    '/news/mse': ['DA1Y1'],
    '/news/ncms': ['DA1Y1'],
    '/news/saee': ['DA1Y1'],
    '/news/scce': ['DA1Y1'],
    '/news/sd': ['DA1Y1'],
    '/news/seee': ['DA1Y1'],
    '/news/sem': ['DA1Y1'],
    '/news/sfs': ['DA1Y1'],
    '/news/shuli': ['DA1Y1'],
    '/news/skl': ['DA1Y1'],
    '/news/slam': ['DA1Y1'],
    '/news/wenfa': ['DA1Y1'],
};
