module.exports = {
    '/comments/:user/:repo/:type/:number': ['TonyRL'],
    '/repos/:user': ['DIYgod'],
    '/trending/:since/:language?/:spoken_language?': ['DIYgod'],
    '/topics/:name/:qs?': ['queensferryme'],
    '/issue/:user/:repo/:state?/:labels?': ['HenryQW', 'AndreyMZ'],
    '/pull/:user/:repo': ['hashman'],
    '/user/followers/:user': ['HenryQW'],
    '/stars/:user/:repo': ['HenryQW'],
    '/branches/:user/:repo': ['max-arnold'],
    '/file/:user/:repo/:branch/:filepath+': ['zengxs'],
    '/search/:query/:sort?/:order?': ['LogicJake'],
    '/starred_repos/:user': ['LanceZhu'],
    '/contributors/:user/:repo/:order?/:anon?': ['zoenglinghou'],
};
