module.exports = {
    '/branches/:user/:repo': ['max-arnold'],
    '/comments/:user/:repo/:number': ['TonyRL'],
    '/contributors/:user/:repo/:order?/:anon?': ['zoenglinghou'],
    '/file/:user/:repo/:branch/:filepath+': ['zengxs'],
    '/issue/:user/:repo/:state?/:labels?': ['HenryQW', 'AndreyMZ'],
    '/notifications': ['zhzy0077'],
    '/pull/:user/:repo/:state?': ['hashman', 'TonyRL'],
    '/repos/:user': ['DIYgod'],
    '/search/:query/:sort?/:order?': ['LogicJake'],
    '/starred_repos/:user': ['LanceZhu'],
    '/stars/:user/:repo': ['HenryQW'],
    '/topics/:name/:qs?': ['queensferryme'],
    '/trending/:since/:language/:spoken_language?': ['DIYgod', 'jameschensmith'],
    '/user/followers/:user': ['HenryQW'],
    '/wiki/:user/:repo/:page?': ['TonyRL'],
};
