module.exports = {
    '/movie/playing': ['DIYgod'],
    '/movie/playing/:score': ['DIYgod'],
    '/movie/later': ['DIYgod'],
    '/movie/ustop': ['DIYgod'],
    '/movie/weekly/:type?': ['numm233', 'nczitzk'],
    '/movie/classification/:sort?/:score?/:tags?': ['zzwab'],
    '/celebrity/:id/:sort?': ['minimalistrojan'],
    '/group/:groupid/:type?': ['DIYgod'],
    '/explore': ['clarkzsd'],
    '/explore_column/:id': ['LogicJake'],
    '/book/latest': ['fengkx'],
    '/music/latest/:area?': ['fengkx', 'xyqfer'],
    '/event/hot/:locationId': ['xyqfer'],
    '/commercialpress/latest': ['xyqfer'],
    '/bookstore': ['xyqfer'],
    '/book/rank/:type?': ['xyqfer', 'queensferryme'],
    '/doulist/:id': ['LogicJake'],
    '/people/:userid/status/:routeParams': ['alfredcai'],
    '/replies/:uid': ['nczitzk'],
    '/replied/:uid': ['nczitzk'],
    '/topic/:id/:sort?': ['LogicJake'],
    '/channel/:id/:nav?': ['umm233'],
    '/channel/:id/subject/:nav': ['umm233'],
    '/people/:userid/wish/:routeParams?': ['exherb'],
    '/jobs/:type': ['Fatpandac'],
};
