module.exports = {
    'whu.edu.cn': {
        _name: '武汉大学',
        cs: [
            {
                title: '计算机学院公告',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue',
            },
        ],
        gs: [
            {
                title: '研究生院',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-yan-jiu-sheng-yuan',
                source: ['/index.htm', '/'],
                target: '/whu/gs',
            },
        ],
        hyxt: [
            {
                title: '弘毅学堂 - 新闻动态',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xwdt'],
                target: '/whu/hyxt/xwdt',
            },
            {
                title: '弘毅学堂 - 通知公告',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/tzgg'],
                target: '/whu/hyxt/tzgg',
            },
            {
                title: '弘毅学堂 - 学子风采',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xzfc'],
                target: '/whu/hyxt/xzfc',
            },
            {
                title: '弘毅学堂 - 学术论坛',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xslt'],
                target: '/whu/hyxt/xslt',
            },
            {
                title: '弘毅学堂 - 学堂简报',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xtjb'],
                target: '/whu/hyxt/xtjb',
            },
            {
                title: '弘毅学堂 - 人才培养',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/rcpy'],
                target: '/whu/hyxt/rcpy',
            },
            {
                title: '弘毅学堂 - 招生工作',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/rcpy/zsgz', '/rcpy'],
                target: '/whu/hyxt/rcpy/zsgz',
            },
            {
                title: '弘毅学堂 - 培养方案',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/rcpy/pyfa', '/rcpy'],
                target: '/whu/hyxt/rcpy/pyfa',
            },
            {
                title: '弘毅学堂 - 科研训练',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/rcpy/kyxl', '/rcpy'],
                target: '/whu/hyxt/rcpy/kyxl',
            },
            {
                title: '弘毅学堂 - 毕业去向',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/rcpy/byqx', '/rcpy'],
                target: '/whu/hyxt/rcpy/byqx',
            },
            {
                title: '弘毅学堂 - 学习资源',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/rcpy/xxzy', '/rcpy'],
                target: '/whu/hyxt/rcpy/xxzy',
            },
            {
                title: '弘毅学堂 - 学生工作',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xsgz'],
                target: '/whu/hyxt/xsgz',
            },
            {
                title: '弘毅学堂 - 党团建设',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xsgz/dtjs', '/xsgz'],
                target: '/whu/hyxt/xsgz/dtjs',
            },
            {
                title: '弘毅学堂 - 学术交流',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xsgz/xsjl', '/xsgz'],
                target: '/whu/hyxt/xsgz/xsjl',
            },
            {
                title: '弘毅学堂 - 书院生活',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xsgz/sysh', '/xsgz'],
                target: '/whu/hyxt/xsgz/sysh',
            },
            {
                title: '弘毅学堂 - 奖助体系',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xsgz/jztx', '/xsgz'],
                target: '/whu/hyxt/xsgz/jztx',
            },
            {
                title: '弘毅学堂 - 事务服务',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xsgz/swfw', '/xsgz'],
                target: '/whu/hyxt/xsgz/swfw',
            },
            {
                title: '弘毅学堂 - 国际合作',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/gjhz'],
                target: '/whu/hyxt/gjhz',
            },
            {
                title: '弘毅学堂 - 国际交流',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/gjhz/gjjl', '/gjhz'],
                target: '/whu/hyxt/gjhz/gjjl',
            },
            {
                title: '弘毅学堂 - 交流分享',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/gjhz/jlfx', '/gjhz'],
                target: '/whu/hyxt/gjhz/jlfx',
            },
            {
                title: '弘毅学堂 - 校友风采',
                docs: 'https://docs.rsshub.app/routes/university#wu-han-da-xue-hong-yi-xue-tang',
                source: ['/xyfc'],
                target: '/whu/hyxt/xyfc',
            },
        ],
        news: [
            {
                title: '新闻网 - 武大资讯',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/wdzx/wdyw', '/wdzx'],
                target: '/whu/news/wdzx/wdyw',
            },
            {
                title: '新闻网 - 武大要闻',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/wdzx/wdyw', '/wdzx'],
                target: '/whu/news/wdzx/wdyw',
            },
            {
                title: '新闻网 - 综合新闻',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/wdzx/zhxw', '/wdzx'],
                target: '/whu/news/wdzx/zhxw',
            },
            {
                title: '新闻网 - 合作交流',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/wdzx/hzjl', '/wdzx'],
                target: '/whu/news/wdzx/hzjl',
            },
            {
                title: '新闻网 - 一线传真',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/wdzx/yxcz', '/wdzx'],
                target: '/whu/news/wdzx/yxcz',
            },
            {
                title: '新闻网 - 学术动态',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/kydt'],
                target: '/whu/news/kydt',
            },
            {
                title: '新闻网 - 校园文化',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/xywh/bfxy', '/xywh'],
                target: '/whu/news/xywh/bfxy',
            },
            {
                title: '新闻网 - 缤纷校园',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/xywh/bfxy', '/xywh'],
                target: '/whu/news/xywh/bfxy',
            },
            {
                title: '新闻网 - 校友之声',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/xywh/xyzs', '/xywh'],
                target: '/whu/news/xywh/xyzs',
            },
            {
                title: '新闻网 - 珞珈副刊',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/xywh/ljfk', '/xywh'],
                target: '/whu/news/xywh/ljfk',
            },
            {
                title: '新闻网 - 校史钩沉',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/xywh/xsgc', '/xywh'],
                target: '/whu/news/xywh/xsgc',
            },
            {
                title: '新闻网 - 主题教育',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/ztbd/ztjy', '/ztbd'],
                target: '/whu/news/ztbd/ztjy',
            },
            {
                title: '新闻网 - 顶天立地建学科',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/ztbd/dtldjxk', '/ztbd'],
                target: '/whu/news/ztbd/dtldjxk',
            },
            {
                title: '新闻网 - 学习在线',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/ztbd/xxzx', '/ztbd'],
                target: '/whu/news/ztbd/xxzx',
            },
            {
                title: '新闻网 - 记者调查',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/ztbd/jzdc', '/ztbd'],
                target: '/whu/news/ztbd/jzdc',
            },
            {
                title: '新闻网 - 校庆征文 我与武大',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/ztbd/xqzw_wywd', '/ztbd'],
                target: '/whu/news/ztbd/xqzw_wywd',
            },
            {
                title: '新闻网 - 媒体武大',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/mtwd'],
                target: '/whu/news/mtwd',
            },
            {
                title: '新闻网 - 珞珈人物',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/ljrw'],
                target: '/whu/news/ljrw',
            },
            {
                title: '新闻网 - 视听空间',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/stkj/ljyx', '/stkj'],
                target: '/whu/media/stkj/ljyx',
            },
            {
                title: '新闻网 - 珞珈影像',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/stkj/ljyx', '/stkj'],
                target: '/whu/media/stkj/ljyx',
            },
            {
                title: '新闻网 - 武大视频',
                docs: 'https://docs.rsshub.app/routes/wu-han-da-xue#wu-han-da-xue-xin-wen-wang',
                source: ['/stkj/wdsp', '/stkj'],
                target: '/whu/media/stkj/wdsp',
            },
        ],
    },
};
