module.exports = {
    '8264.com': {
        _name: '8264',
        '.': [
            {
                title: '热门推荐',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/751'],
                target: '/8264/list/751',
            },
            {
                title: '户外知识',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/238'],
                target: '/8264/list/238',
            },
            {
                title: '户外装备',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/204'],
                target: '/8264/list/204',
            },
            {
                title: '业界',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/489'],
                target: '/8264/list/489',
            },
            {
                title: '国际',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/733'],
                target: '/8264/list/733',
            },
            {
                title: '专访',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/746'],
                target: '/8264/list/746',
            },
            {
                title: '图说',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/902'],
                target: '/8264/list/902',
            },
            {
                title: '户外',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/914'],
                target: '/8264/list/914',
            },
            {
                title: '登山',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/934'],
                target: '/8264/list/934',
            },
            {
                title: '攀岩',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/935'],
                target: '/8264/list/935',
            },
            {
                title: '徒步',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/242'],
                target: '/8264/list/242',
            },
            {
                title: '露营',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/950'],
                target: '/8264/list/950',
            },
            {
                title: '安全急救',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/931'],
                target: '/8264/list/931',
            },
            {
                title: '领队',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/920'],
                target: '/8264/list/920',
            },
            {
                title: '登雪山',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/915'],
                target: '/8264/list/915',
            },
            {
                title: '攀岩',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/916'],
                target: '/8264/list/916',
            },
            {
                title: '骑行',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/917'],
                target: '/8264/list/917',
            },
            {
                title: '跑步',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/918'],
                target: '/8264/list/918',
            },
            {
                title: '滑雪',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/919'],
                target: '/8264/list/919',
            },
            {
                title: '水上运动',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/921'],
                target: '/8264/list/921',
            },
            {
                title: '钓鱼',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/951'],
                target: '/8264/list/951',
            },
            {
                title: '潜水',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/952'],
                target: '/8264/list/952',
            },
            {
                title: '攀冰',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/953'],
                target: '/8264/list/953',
            },
            {
                title: '冲浪',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/966'],
                target: '/8264/list/966',
            },
            {
                title: '网球',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/967'],
                target: '/8264/list/967',
            },
            {
                title: '绳索知识',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/968'],
                target: '/8264/list/968',
            },
            {
                title: '高尔夫',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/969'],
                target: '/8264/list/969',
            },
            {
                title: '马术',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/970'],
                target: '/8264/list/970',
            },
            {
                title: '户外摄影',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/973'],
                target: '/8264/list/973',
            },
            {
                title: '羽毛球',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/971'],
                target: '/8264/list/971',
            },
            {
                title: '游泳',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/974'],
                target: '/8264/list/974',
            },
            {
                title: '溯溪',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/975'],
                target: '/8264/list/975',
            },
            {
                title: '健身',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/976'],
                target: '/8264/list/976',
            },
            {
                title: '瑜伽',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/977'],
                target: '/8264/list/977',
            },
            {
                title: '服装',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/209'],
                target: '/8264/list/209',
            },
            {
                title: '冲锋衣',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/923'],
                target: '/8264/list/923',
            },
            {
                title: '抓绒衣',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/924'],
                target: '/8264/list/924',
            },
            {
                title: '皮肤衣',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/925'],
                target: '/8264/list/925',
            },
            {
                title: '速干衣',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/926'],
                target: '/8264/list/926',
            },
            {
                title: '羽绒服',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/927'],
                target: '/8264/list/927',
            },
            {
                title: '软壳',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/929'],
                target: '/8264/list/929',
            },
            {
                title: '户外鞋',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/211'],
                target: '/8264/list/211',
            },
            {
                title: '登山鞋',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/928'],
                target: '/8264/list/928',
            },
            {
                title: '徒步鞋',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/930'],
                target: '/8264/list/930',
            },
            {
                title: '越野跑鞋',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/933'],
                target: '/8264/list/933',
            },
            {
                title: '溯溪鞋',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/932'],
                target: '/8264/list/932',
            },
            {
                title: '登山杖',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/220'],
                target: '/8264/list/220',
            },
            {
                title: '帐篷',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/208'],
                target: '/8264/list/208',
            },
            {
                title: '睡袋',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/212'],
                target: '/8264/list/212',
            },
            {
                title: '炉具',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/792'],
                target: '/8264/list/792',
            },
            {
                title: '灯具',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/218'],
                target: '/8264/list/218',
            },
            {
                title: '水具',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/219'],
                target: '/8264/list/219',
            },
            {
                title: '面料',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/222'],
                target: '/8264/list/222',
            },
            {
                title: '背包',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/207'],
                target: '/8264/list/207',
            },
            {
                title: '防潮垫',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/214'],
                target: '/8264/list/214',
            },
            {
                title: '电子导航',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/216'],
                target: '/8264/list/216',
            },
            {
                title: '冰岩绳索',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/215'],
                target: '/8264/list/215',
            },
            {
                title: '综合装备',
                docs: 'https://docs.rsshub.app/routes/new-media#8264-lie-biao',
                source: ['/list/223'],
                target: '/8264/list/223',
            },
        ],
    },
};
