const config = {
    bwc: { title: '武装部保卫处', id: 'tzgg' },
    career: { title: '本科就业信息网', id: 'tzgg', listSelector: 'ul.newsList', pubDateSelector: 'li[class="span2 y"]', descriptionSelector: '.aContent' },
    cyb: { title: '资产经营公司/产业办', id: '367' },
    dangban: { title: '党委办公室', id: '4014' },
    djfwzxdcs: { title: '党建服务中心/党建督查室', id: 'tzgg', listSelector: '.news', pubDateSelector: 'span[class="news_meta"]' },
    dqxy: { title: '电气工程学院', id: '2462' },
    dwllc: { title: '对外联络处', id: '2649' },
    dxxy: { title: '电子与信息工程学院', id: 'tzgg', pubDateSelector: 'div[class="article-publishdate"]' },
    energy: { title: '能源与机械工程学院', id: '892' },
    'energy-saving': { title: '上海热交换系统节能工程技术研究中心', id: 'tzgg' },
    english: { title: 'Shanghai University of Electric Power', id: 'events' },
    fao: { title: '国际交流与合作处（港澳台办公室）', id: 'tzgg' },
    fgw: { title: '妇工委', id: '1411' },
    fzghc: { title: '发展规划处', id: '291' },
    gec: { title: '上海新能源人才技术教育交流中心', id: '1959' },
    gonghui: { title: '工会', id: '1806', listSelector: 'table.wp_article_list_table tr', pubDateSelector: 'td[align="right"]' },
    'green-energy': { title: '上海绿色能源并网技术研究中心', id: '118' },
    hhsyzx: { title: '能源化学实验教学中心', id: '3709' },
    hhxy: { title: '环境与化学工程学院', id: '1231' },
    hqglc: { title: '后勤管理处（后勤服务中心）', id: '1616' },
    ieetc: { title: '创新创业工程训练中心', id: 'cxcy', pubDateSelector: 'div[class="article-publishdate"]' },
    jgdw: { title: '机关党委', id: '3205' },
    jgxy: { title: '经济与管理学院', id: '3633' },
    jijian: { title: '纪委（监察专员办公室）', id: '59' },
    jjc: { title: '基建处', id: '327' },
    jjxy: { title: '继续教育学院（国际教育学院）', id: '2582' },
    jsjxfzzx: { title: '教师教学发展中心', id: '3909' },
    jsjxy: { title: '计算机科学与技术学院', id: '973' },
    jszyzx: { title: '技术转移中心', id: '4247' },
    jwc: { title: '教务处', id: '227' },
    kczx: { title: '能源电力科创中心', id: '3946' },
    kyc: { title: '科研处/融合办', id: '834' },
    lgxq: { title: '临港新校区建设综合办公室', id: '377' },
    library: { title: '图书馆', id: '4866' },
    metc: { title: '现代教育技术中心/信息办', id: 'tzgg', pubDateSelector: 'div[class="article-publishdate"]' },
    mpep: { title: '上海市电力材料防护与新材料重点实验室', id: '1134' },
    news: { title: '新闻网', id: 'notice' },
    office: { title: '校长办公室（档案馆）', id: '389' },
    rsc: { title: '党委教师工作部/人事处', id: '1695' },
    rwysxy: { title: '人文艺术学院', id: '3089' },
    sjc: { title: '审计处', id: '199' },
    skb: { title: '马克思主义学院', id: '1736' },
    slxy: { title: '数理学院', id: '2063' },
    sysyzcglc: { title: '实验室与资产管理处', id: '312' },
    tgb: { title: '离退休党委/退管办', id: 'notice', pubDateSelector: 'div[class="article-publishdate"]' },
    tw: { title: '团委', id: '2092' },
    tyb: { title: '体育学院', id: '2891' },
    tzb: { title: '统战部', id: '3858' },
    wenming: { title: '文明办', id: '2202' },
    wgyxy: { title: '外国语学院', id: 'tzgg' },
    xcb: { title: '宣传部（文明办、融媒体中心）', id: '2925' },
    xsc: { title: '学生处', id: '3482' },
    xunchaban: { title: '巡查办', id: '5044' },
    xxgk: { title: '信息公开网', id: 'zxgkxx' },
    yjsc: { title: '研究生院/研工部', id: '1161' },
    zdhxy: { title: '自动化工程学院', id: '2002' },
    zs: { title: '本科招生网', id: 'zxxx' },
    zzb: { title: '组织部（老干部处、党校）', id: '1534' },
};

module.exports = {
    config,
};
