module.exports = {
    '/app/:id?': ['nczitzk'],
    '/audio/:id': ['LogicJake'],
    '/blackboard': ['Qixingchen'],
    '/bangumi/:seasonid': ['DIYgod'],
    '/bangumi/media/:mediaid': ['DIYgod'],
    '/channel/:channelid/hot/:disableEmbed?': ['3401797899'],
    '/fav/:uid/:fid/:disableEmbed?': ['Qixingchen'],
    '/followings/article/:uid': ['woshiluo'],
    '/followings/dynamic/:uid/:routeParams?': ['TigerCubDen', 'JimenezLi'],
    '/followings/video/:uid/:disableEmbed?': ['LogicJake'],
    '/hot-search': ['CaoMeiYouRen'],
    '/link/news/:product': ['Qixingchen'],
    '/live/area/:areaID/:order': ['Qixingchen'],
    '/live/room/:roomID': ['Qixingchen'],
    '/live/search/:key/:order': ['Qixingchen'],
    '/mall/new/:category?': ['DIYgod'],
    '/mall/ip/:id': ['DIYgod'],
    '/manga/update/:comicid': ['hoilc'],
    '/manga/followings/:uid/:limits?': ['yindaheng98'],
    '/online/:disableEmbed?': ['TigerCubDen'],
    '/partion/:tid/:disableEmbed?': ['DIYgod'],
    '/partion/ranking/:tid/:days?/:disableEmbed?': ['lengthmin'],
    '/popular/all': ['ziminliu'],
    '/ranking/:rid?/:day?/:arc_type?/:disableEmbed?': ['DIYgod'],
    '/readlist/:listid': ['hoilc'],
    '/topic/:topic': ['Qixingchen'],
    '/user/article/:uid': ['lengthmin'],
    '/user/bangumi/:uid/:type?': ['wdssmq'],
    '/user/channel/:uid/:sid/:disableEmbed?': ['weirongxu'],
    '/user/coin/:uid/:disableEmbed?': ['DIYgod'],
    '/user/collection/:uid/:sid/:disableEmbed?': ['shininome'],
    '/user/dynamic/:uid/:routeParams?': ['DIYgod', 'zytomorrow', 'CaoMeiYouRen', 'JimenezLi'],
    '/user/fav/:uid/:disableEmbed?': ['DIYgod'],
    '/user/followers/:uid/:loginUid': ['Qixingchen'],
    '/user/followings/:uid/:loginUid': ['Qixingchen'],
    '/user/video/:uid/:disableEmbed?': ['DIYgod'],
    '/user/video-all/:uid/:disableEmbed?': ['CcccFz'],
    '/video/danmaku/:bvid/:pid?': ['Qixingchen'],
    '/video/page/:bvid/:disableEmbed?': ['sxzz'],
    '/video/reply/:bvid': ['Qixingchen'],
    '/vsearch/:kw/:order?/:disableEmbed?/:tid?': ['Symty'],
    '/watchlater/:uid/:disableEmbed?': ['JimenezLi'],
    '/weekly/:disableEmbed?': ['ttttmr'],
};
