export default {
    'transcriptforest.com': {
        _name: 'Transcript Forest',
        www: [
            {
                title: 'All',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel'],
                target: '/transcriptforest',
            },
            {
                title: 'a16z podcast',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/a16z-podcast'],
                target: '/transcriptforest/a16z-podcast',
            },
            {
                title: "Aarthi and Sriram's Good Time Show",
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/aarthi-and-srirams-good-time-show'],
                target: '/transcriptforest/aarthi-and-srirams-good-time-show',
            },
            {
                title: 'Acquired',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/acquired'],
                target: '/transcriptforest/acquired',
            },
            {
                title: 'All-In with Chamath, Jason, Sacks & Friedberg',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/all-in-with-chamath-jason-sacks-friedberg'],
                target: '/transcriptforest/all-in-with-chamath-jason-sacks-friedberg',
            },
            {
                title: 'All the Hacks',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/all-the-hacks'],
                target: '/transcriptforest/all-the-hacks',
            },
            {
                title: 'Breaking Points',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/breaking-points'],
                target: '/transcriptforest/breaking-points',
            },
            {
                title: 'Cartoon Avatars',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/cartoon-avatars'],
                target: '/transcriptforest/cartoon-avatars',
            },
            {
                title: 'Conversations With Coleman',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/conversations-with-coleman'],
                target: '/transcriptforest/conversations-with-coleman',
            },
            {
                title: 'CSPI Podcast',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/cspi-podcast'],
                target: '/transcriptforest/cspi-podcast',
            },
            {
                title: 'Culpable',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/culpable'],
                target: '/transcriptforest/culpable',
            },
            {
                title: 'Dateline NBC',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/dateline-nbc'],
                target: '/transcriptforest/dateline-nbc',
            },
            {
                title: 'Execs',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/execs'],
                target: '/transcriptforest/execs',
            },
            {
                title: 'Exponent',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/exponent'],
                target: '/transcriptforest/exponent',
            },
            {
                title: 'Freakonomics',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/freakonomics'],
                target: '/transcriptforest/freakonomics',
            },
            {
                title: 'Future of StoryTelling',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/future-of-storytelling'],
                target: '/transcriptforest/future-of-storytelling',
            },
            {
                title: 'Gamecraft',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/gamecraft'],
                target: '/transcriptforest/gamecraft',
            },
            {
                title: 'Get WIRED',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/get-wired'],
                target: '/transcriptforest/get-wired',
            },
            {
                title: 'Greymatter',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/greymatter'],
                target: '/transcriptforest/greymatter',
            },
            {
                title: 'How I built this',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/how-I-built-this'],
                target: '/transcriptforest/how-I-built-this',
            },
            {
                title: 'Huberman Lab',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/huberman-lab'],
                target: '/transcriptforest/huberman-lab',
            },
            {
                title: 'ICYMI',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/icymi'],
                target: '/transcriptforest/icymi',
            },
            {
                title: 'In Machines We Trust',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/in-machines-we-trust'],
                target: '/transcriptforest/in-machines-we-trust',
            },
            {
                title: "Invest Like the Best with Patrick O'Shaughnessy",
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/invest-like-the-best-with-patrick-o-shaughnessy'],
                target: '/transcriptforest/invest-like-the-best-with-patrick-o-shaughnessy',
            },
            {
                title: 'Joe Rogan Experience Review podcast',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/joe-rogan-experience-review-podcast'],
                target: '/transcriptforest/joe-rogan-experience-review-podcast',
            },
            {
                title: 'Land of Giants',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/land-of-giants'],
                target: '/transcriptforest/land-of-giants',
            },
            {
                title: "Lenny's Podcast: Product | Growth | Career",
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/lenny-podcast-product-growth-career'],
                target: '/transcriptforest/lenny-podcast-product-growth-career',
            },
            {
                title: 'Lex Fridman Podcast',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/lex-fridman-podcast'],
                target: '/transcriptforest/lex-fridman-podcast',
            },
            {
                title: 'Making Sense with Sam Harris',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/making-sense-with-sam-harris'],
                target: '/transcriptforest/making-sense-with-sam-harris',
            },
            {
                title: 'Masters of Scale',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/masters-of-scale'],
                target: '/transcriptforest/masters-of-scale',
            },
            {
                title: 'Modern Wisdom',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/modern-wisdom'],
                target: '/transcriptforest/modern-wisdom',
            },
            {
                title: 'Moment of Zen',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/moment-of-zen'],
                target: '/transcriptforest/moment-of-zen',
            },
            {
                title: 'Morbid',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/morbid'],
                target: '/transcriptforest/morbid',
            },
            {
                title: 'My First Million',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/my-first-million'],
                target: '/transcriptforest/my-first-million',
            },
            {
                title: 'Naval',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/naval'],
                target: '/transcriptforest/naval',
            },
            {
                title: 'Newcomer Podcast',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/newcomer-podcast'],
                target: '/transcriptforest/newcomer-podcast',
            },
            {
                title: 'Not investment advice',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/not-investment-advice'],
                target: '/transcriptforest/not-investment-advice',
            },
            {
                title: 'Odd Lots',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/odd-lots'],
                target: '/transcriptforest/odd-lots',
            },
            {
                title: 'On with Kara Swisher',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/on-with-kara-swisher'],
                target: '/transcriptforest/on-with-kara-swisher',
            },
            {
                title: 'Proof: A True Crime Podcast',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/proof-a-true-crime-podcast'],
                target: '/transcriptforest/proof-a-true-crime-podcast',
            },
            {
                title: 'Reply All',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/reply-all'],
                target: '/transcriptforest/reply-all',
            },
            {
                title: 'Revisionist History',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/revisionist-history'],
                target: '/transcriptforest/revisionist-history',
            },
            {
                title: 'Serial',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/serial-podcast'],
                target: '/transcriptforest/serial-podcast',
            },
            {
                title: 'Slow Burn',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/slow-burn'],
                target: '/transcriptforest/slow-burn',
            },
            {
                title: 'StrictlyVC Download',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/strictlyvc-download'],
                target: '/transcriptforest/strictlyvc-download',
            },
            {
                title: 'Stuff You Should Know:',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/stuff-you-should-know'],
                target: '/transcriptforest/stuff-you-should-know',
            },
            {
                title: 'Subversive w/Alex Kaschuta',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/subversive-w-alex-kaschuta'],
                target: '/transcriptforest/subversive-w-alex-kaschuta',
            },
            {
                title: 'TED Radio Hour',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/ted-radio-hour'],
                target: '/transcriptforest/ted-radio-hour',
            },
            {
                title: 'The Bootstrapped Founder',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/the-bootstrapped-founder'],
                target: '/transcriptforest/the-bootstrapped-founder',
            },
            {
                title: 'The Boyscast with Ryan Long',
                docs: 'https://docs.rsshub.app/routes/multimedia#transcript-forest',
                source: ['/en/channel/the-boyscast-with-ryan-long'],
                target: '/transcriptforest/the-boyscast-with-ryan-long',
            },
        ],
    },
};
