/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: '.',
        },
    ],
    guideSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'category',
            label: 'Guide',
            items: ['README', 'usage', 'instances', 'faq', 'parameter', 'api'],
            collapsible: true,
            collapsed: true,
        },
        {
            type: 'category',
            label: 'Routes',
            link: {
                type: 'generated-index',
                slug: '/routes',
                description: 'Routes are the access paths of RSSHub. Each route contains a RSSHub rule, which tells RSSHub how to extract content from the website and generate RSS subscription.',
            },
            items: [
                {
                    type: 'doc',
                    id: 'routes/social-media',
                    label: '💬 Social Media',
                },
                {
                    type: 'doc',
                    id: 'routes/new-media',
                    label: '📱 New media',
                },
                {
                    type: 'doc',
                    id: 'routes/traditional-media',
                    label: '📰 News',
                },
                {
                    type: 'doc',
                    id: 'routes/bbs',
                    label: '💬️ BBS',
                },
                {
                    type: 'doc',
                    id: 'routes/blog',
                    label: '🖊️️ Blog',
                },
                {
                    type: 'doc',
                    id: 'routes/programming',
                    label: '💻 Programming',
                },
                {
                    type: 'doc',
                    id: 'routes/design',
                    label: '🎨️ Design',
                },
                {
                    type: 'doc',
                    id: 'routes/live',
                    label: '🎥 Live',
                },
                {
                    type: 'doc',
                    id: 'routes/multimedia',
                    label: '🔊 Multimedia',
                },
                {
                    type: 'doc',
                    id: 'routes/picture',
                    label: '🖼️ Picture',
                },
                {
                    type: 'doc',
                    id: 'routes/anime',
                    label: '🎨️ ACG',
                },
                {
                    type: 'doc',
                    id: 'routes/program-update',
                    label: '🔄 Application Updates',
                },
                {
                    type: 'doc',
                    id: 'routes/university',
                    label: '🎓 University',
                },
                {
                    type: 'doc',
                    id: 'routes/forecast',
                    label: '❗️ Forecast and Alerts',
                },
                {
                    type: 'doc',
                    id: 'routes/travel',
                    label: '🛫 Travel',
                },
                {
                    type: 'doc',
                    id: 'routes/shopping',
                    label: '🛍️ Shopping',
                },
                {
                    type: 'doc',
                    id: 'routes/game',
                    label: '🎮 Gaming',
                },
                {
                    type: 'doc',
                    id: 'routes/reading',
                    label: '📚 Reading',
                },
                {
                    type: 'doc',
                    id: 'routes/government',
                    label: '📢 Government',
                },
                {
                    type: 'doc',
                    id: 'routes/study',
                    label: '📖 Study',
                },
                {
                    type: 'doc',
                    id: 'routes/journal',
                    label: '🔬 Scientific Journal',
                },
                {
                    type: 'doc',
                    id: 'routes/finance',
                    label: '💰 Finance',
                },
                {
                    type: 'doc',
                    id: 'routes/other',
                    label: '🔍 Uncategorized',
                },
            ],
            collapsible: false,
        },
    ],
    joinusSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'joinus',
        },
    ],
    installSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'install',
        },
    ],
    supportSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'support',
        },
    ],
};

export default sidebars;
