/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: '.',
        },
    ],
    guideSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'category',
            label: '指南',
            items: ['README', 'usage', 'faq', 'parameter', 'api'],
            collapsible: true,
            collapsed: true,
        },
        {
            type: 'category',
            label: '路由',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'routes',
                },
            ],
            collapsible: false,
        },
    ],
    joinusSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'joinus',
        },
    ],
    installSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'install',
        },
    ],
    supportSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'support',
        },
    ],
};

module.exports = sidebars;
