/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: '.',
        },
    ],
    guideSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'category',
            label: '指南',
            items: ['README', 'usage', 'faq', 'parameter', 'api'],
            collapsible: true,
            collapsed: true,
        },
        {
            type: 'category',
            label: '路由',
            link: {
                type: 'generated-index',
                slug: '/routes',
                description: '路由是 RSSHub 访问路径，每个路由后面包含一段 RSSHub 规则，它告诉 RSSHub 如何从网站中提取内容并生成 RSS 订阅。',
            },
            items: [
                'routes/social-media',
                'routes/new-media',
                'routes/traditional-media',
                'routes/bbs',
                'routes/blog',
                'routes/programming',
                'routes/design',
                'routes/live',
                'routes/multimedia',
                'routes/picture',
                'routes/anime',
                'routes/program-update',
                'routes/university',
                'routes/forecast',
                'routes/travel',
                'routes/shopping',
                'routes/game',
                'routes/reading',
                'routes/government',
                'routes/study',
                'routes/journal',
                'routes/finance',
                'routes/other',
            ],
            collapsible: false,
        },
    ],
    joinusSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'joinus',
        },
    ],
    installSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'install',
        },
    ],
    supportSidebar: [
        {
            type: 'html',
            value: 'CarbonAds',
        },
        {
            type: 'autogenerated',
            dirName: 'support',
        },
    ],
};

module.exports = sidebars;
