module.exports = {
    '/': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/genre/:id': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/label/:id': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu', 'nczitzk'],
    '/series/:id': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu', 'nczitzk'],
    '/star/:id': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/studio/:id': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu', 'nczitzk'],
    '/search/:keyword': ['nczitzk'],
    '/uncensored': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/uncensored/genre/:id': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/uncensored/series/:id': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu', 'nczitzk'],
    '/uncensored/star/:id': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/uncensored/search/:keyword': ['nczitzk'],
    '/western': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/western/genre/:gid': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/western/series/:seriesid': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu', 'nczitzk'],
    '/western/star/:sid': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/western/search/:keyword': ['nczitzk'],
};
