module.exports = {
    '/': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/genre/:gid': ['MegrezZhu', 'CoderTonyChan'],
    '/home': ['MegrezZhu', 'CoderTonyChan'],
    '/label/:labelid': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu'],
    '/series/:seriesid': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu'],
    '/star/:sid': ['MegrezZhu', 'CoderTonyChan'],
    '/studio/:studioid': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu'],
    '/uncensored/home': ['MegrezZhu', 'CoderTonyChan'],
    '/uncensored/genre/:gid': ['MegrezZhu', 'CoderTonyChan'],
    '/uncensored/series/:seriesid': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu'],
    '/uncensored/star/:sid': ['MegrezZhu', 'CoderTonyChan'],
    '/western': ['MegrezZhu', 'CoderTonyChan', 'nczitzk'],
    '/western/home': ['MegrezZhu', 'CoderTonyChan'],
    '/western/genre/:gid': ['MegrezZhu', 'CoderTonyChan'],
    '/western/series/:seriesid': ['MegrezZhu', 'CoderTonyChan', 'Felix2yu'],
    '/western/star/:sid': ['MegrezZhu', 'CoderTonyChan'],
};
