name: 'Clean up GHCR Packages'

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
    cleanup:
        runs-on: ubuntu-slim
        permissions:
            packages: write
            contents: read
        steps:
            - name: Delete old container versions (30+ days)
              uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1.2.2
              with:
                  dry-run: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  package: rsshub
                  older-than: 30 days
                  keep-n-tagged: 5
                  delete-untagged: true
                  delete-ghost-images: true
                  delete-orphaned-images: true
                  delete-partial-images: true
