on:
  push

jobs:
  sync_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: DIYgod/RSSHub
          target_repository: ''
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
