module.exports = {
    // ministry
    '/customs/list/:gchannel?': ['Jeason0228', 'TonyRL'],
    '/fmprc/:category?': ['nicolaszf', 'nczitzk'],
    '/immiau/news': ['liu233w'],
    '/mee/ywdt?': ['liuxsdev'],
    '/mfa/wjdt/:category?': ['nczitzk'],
    '/miit/wjfb/:ministry': ['Fatpandac'],
    '/miit/yjzj': ['Fatpandac'],
    '/miit/zcwj': ['Yoge-Code'],
    '/miit/wjgs': ['Yoge-Code'],
    '/miit/zcjd': ['Yoge-Code'],
    '/moe/:type': ['Crawler995'],
    '/nrta/news/:category?': ['yuxinliu-alex'],
    '/pbc/goutongjiaoliu': ['nczitzk'],
    '/pbc/gzlw': ['Fatpandac'],
    '/pbc/tradeAnnouncement': ['nczitzk'],
    '/pbc/zcyj': ['Fatpandac'],
    // province
    '/anhui/kjt/:path?': ['nczitzk'],
    '/beijing/jw/tzgg': ['nczitzk'],
    '/beijing/kw/:channel': ['Fatpandac'],
    '/hebei/czt/xwdt/:category?': ['nczitzk'],
    '/shenzhen/hrss/szksy/:caty/:page?': ['zlasd'],
    '/shenzhen/zzb/:caty/:page?': ['zlasd'],
    '/shanghai/rsj/ksxm': ['Fatpandac'],
    '/shanghai/wsjkw/yqtb': ['zcf0508'],
    '/guangdong/tqyb/tfxtq': ['Fatpandac'],
    '/guangdong/tqyb/sncsyjxh': ['Fatpandac'],
    '/huizhou/zwgk/:category?': ['Fatpandac'],
    '/sichuan/deyang/govpulicinfo/:countyName': ['zytomorrow'],
};
