module.exports = {
    // ministry
    '/cmse/xwzx/zhxw': ['nczitzk'],
    '/cmse/xwzx/yzjz': ['nczitzk'],
    '/cmse/gfgg': ['nczitzk'],
    '/cmse/fxrw': ['nczitzk'],
    '/cmse/kjkx/:id': ['nczitzk'],
    '/cmse/gjhz': ['nczitzk'],
    '/cmse/hqsy/:id': ['nczitzk'],
    '/cmse/ztbd/:id': ['nczitzk'],
    '/cmse/kpjy/:id': ['nczitzk'],
    '/cmse/:path+': ['nczitzk'],
    '/cnnic/:path+': ['nczitzk'],
    '/customs/list/:gchannel?': ['Jeason0228', 'TonyRL'],
    '/fmprc/:category?': ['nicolaszf', 'nczitzk'],
    '/immiau/news': ['liu233w'],
    '/mee/ywdt?': ['liuxsdev'],
    '/mfa/wjdt/:category?': ['nczitzk'],
    '/miit/wjfb/:ministry': ['Fatpandac'],
    '/miit/yjzj': ['Fatpandac'],
    '/miit/zcwj': ['Yoge-Code'],
    '/miit/wjgs': ['Yoge-Code'],
    '/miit/zcjd': ['Yoge-Code'],
    '/moe/:type': ['Crawler995'],
    '/moj/aac/news/:type?': ['TonyRL'],
    '/nifdc/:path+': ['nczitzk'],
    '/nmpa/:path+': ['TonyRL'],
    '/nrta/news/:category?': ['yuxinliu-alex'],
    '/nsfc/news/:type?': ['Derekmini', 'nczitzk'],
    '/pbc/goutongjiaoliu': ['nczitzk'],
    '/pbc/gzlw': ['Fatpandac'],
    '/pbc/tradeAnnouncement': ['nczitzk'],
    '/pbc/zcyj': ['Fatpandac'],
    // province
    '/anhui/kjt/:path?': ['nczitzk'],
    '/beijing/jw/tzgg': ['nczitzk'],
    '/beijing/kw/:channel': ['Fatpandac'],
    '/guangdong/tqyb/tfxtq': ['Fatpandac'],
    '/guangdong/tqyb/sncsyjxh': ['Fatpandac'],
    '/hebei/czt/xwdt/:category?': ['nczitzk'],
    '/huizhou/zwgk/:category?': ['Fatpandac'],
    '/shaanxi/kjt/:id?': ['nczitzk'],
    '/shenzhen/hrss/szksy/:caty/:page?': ['zlasd'],
    '/shenzhen/zzb/:caty/:page?': ['zlasd'],
    '/shanghai/rsj/ksxm': ['Fatpandac'],
    '/shanghai/yjj/:path+': ['nczitzk'],
    '/shanghai/wsjkw/yqtb': ['zcf0508'],
    '/sichuan/deyang/govpulicinfo/:countyName': ['zytomorrow'],
    '/taiyuan/rsj/:caty/:page?': ['2PoL'],
    '/xuzhou/hrss/:category?': ['nczitzk'],
};
