module.exports = function (router) {
    router.get(/anhui\/kjt\/([\w\d/-]+)?/, require('./anhui/kjt'));
    router.get('/beijing/kw/:channel', require('./beijing/kw/index'));
    router.get('/shenzhen/hrss/szksy/:caty/:page?', require('./shenzhen/hrss/szksy/index'));
    router.get('/shenzhen/zzb/:caty/:page?', require('./shenzhen/zzb/index'));
    router.get('/shanghai/rsj/ksxm', require('./shanghai/rsj/ksxm'));
    router.get('/shanghai/wsjkw/yqtb', require('./shanghai/wsjkw/yqtb'));
    router.get('/fmprc/:category?', require('./mfa/wjdt'));
    router.get('/guangdong/tqyb/tfxtq', require('./guangdong/tqyb/tfxtq'));
    router.get('/guangdong/tqyb/sncsyjxh', require('./guangdong/tqyb/sncsyjxh'));
    router.get('/huizhou/zwgk/:category?', require('./huizhou/zwgk/index'));
    router.get('/sichuan/deyang/govpulicinfo/:countyName', require('./sichuan/deyang/govpulicinfo'));
    router.get('/mfa/wjdt/:category?', require('./mfa/wjdt'));
    router.get('/miit/wjfb/:ministry', require('./miit/wjfb'));
    router.get('/miit/yjzj', require('./miit/yjzj'));
    router.get('/miit/zcwj', require('./miit/zcwj'));
    router.get('/miit/wjgs', require('./miit/wjgs'));
    router.get('/miit/zcjd', require('./miit/zcjd'));
    router.get('/mee/ywdt/:category?', require('./mee/ywdt'));
    router.get('/pbc/goutongjiaoliu', require('./pbc/goutongjiaoliu'));
    router.get('/pbc/tradeAnnouncement', require('./pbc/tradeAnnouncement'));
    router.get('/pbc/gzlw', require('./pbc/gzlw'));
    router.get('/pbc/zcyj', require('./pbc/zcyj'));
};
